### ISSUE TITLE
Does Blazored.LocalStorage follow SemVer?

### ISSUE THREAD

**Issue by MaxMommersteeg** [Blazored/LocalStorage#100]
Today I updated from version 2.1.6 to 2.2.0 and I noticed my CI-pipeline having trouble.

The `SetItemAsync<T>` method signature on `ILocalStorageService` changed:
* [2.1.6] `Task SetItemAsync<T>(string key, T data);`
* [2.2.0] `ValueTask SetItemAsync<T>(string key, T data);`

Not much of an issue for me, since I can easily make a change. But figured I might give you a heads up. I did not find any documentation about Blazored.LocalStorage acctually following SemVer, based on the version numbers I expected that to be the case.

**Comment by chrissainty** [comment]
We do use semver and this was my mistake, I should have bumped the major version. 

I'm going to use the commit from your PR to do that now. Apologies.

**Comment by MaxMommersteeg** [comment]
No, problem. Glad I didn't build my CI-pipeline for nothing : )

Issue can be closed.
