### ISSUE TITLE
Why does the JsonSerializerOptions not just use the default?

### ISSUE THREAD

**Issue by groogiam** [Blazored/LocalStorage#102]
I'm curios as to why the design decision to use the following serializer options  as default?

```c#
new JsonSerializerOptions
        {
            DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
            IgnoreNullValues = true,
            IgnoreReadOnlyProperties = true,
            PropertyNameCaseInsensitive = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            ReadCommentHandling = JsonCommentHandling.Skip,
            WriteIndented = false
        };
```

instead of just `new JsonSerializerOptions()`

This is at odds with defaults used by the rest of the framework and makes it much more difficult to ensure serializer settings are synchronized between client and server tiers. In order to ensure the settings are matched this means you have to individually set each setting rather than just relying on the defaults and updating the properties that are changed from the framework defaults. This could also be remedied by allowing a setter on the LocalStorageOptions.JsonSerializerOptions  so the options could be reset to the default without resetting each individual property.

**Comment by chrissainty** [comment]
You're testing my memory here, but I believe the settings mimicked the behaviour of Newtonsoft.Json which is far more widely used than the new Json library. So from that perspective, it makes things more compatible.

I'm happy to consider a PR for any improvements you think might be useful.

**Comment by groogiam** [comment]
I double checked and this does not look like the default of NewtonSoft.Json settings. See the following code snippet. I just submitted a PR to allow a setter on the options. This should make it fairly painless to reset the options without have to dig in to the source code and won't result in a breaking change. Hopefully this is acceptable. Thanks for your consideration and your work on this project.

```c#
void Main()
{
	var foo = new MyClass
	{
		MyString = "Hello, World",
		MyInt = 500
	};
	
	Console.WriteLine(JsonConvert.SerializeObject(foo));
}

// Define other methods and classes here
public class MyClass
{
	public string MyString { get; set; }

	public int MyInt { get; set; }
}
```
Output:
`{"MyString":"Hello, World","MyInt":500}`
