### ISSUE TITLE
[Feature Request] Add net5.0 compilation

### ISSUE THREAD

**Issue by jeastham1993** [Blazored/LocalStorage#108]
**Is your feature request related to a problem? Please describe.**
The library cannot be used with a .NET 5.0 Blazor project

**Describe the solution you'd like**
Add net5.0 as a target framework.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by chrissainty** [comment]
@jeastham1993 Are you sure about this? I was testing net5.0 with Blazored Modal and Blazored Modal which targets netstandard2.1, the same as this library, still working in a new Blazor Wasm app targeting net5.0.

**Comment by jeastham1993** [comment]
@chrissainty I've just attempted to update .net standard 2.1 Blazor app to .net 5 RC1 and the only problem I ran into was that Blazored.LocalStorage is only compatible with .net standard 2.1. Seemed a low impact change here to add a .NET 5 compilation.

Happy if you don't want to go down that route though :)

**Comment by chrissainty** [comment]
No I'm happy for the update, I had it on my todo list. But I'm not seeing the same behaviour, things seem to just work without the target change. I'm just trying to work out why we're seeing different things.

**Comment by jeastham1993** [comment]
Nope, if I update my csproj to target net5.0 I get a build error. 

![image](https://user-images.githubusercontent.com/14234617/93760861-b67dfc00-fc04-11ea-88e2-c332131e66d2.png)

**Comment by jeastham1993** [comment]
@chrissainty so, as it turns out if I update my Visual Studio install to the latest preview version I can build the app without needing to update Blazored.LocalStorage. I guess it's because of the way the main VS release supports .NET 5.
