### ISSUE TITLE
[Question]Access to the Storage??

### ISSUE THREAD

**Issue by djaus2** [Blazored/LocalStorage#111]
I am assuming the answer to the following is no:
Can an app, say a .NET Core Console app on the same machine, access the LocalStorage from a PWA app?
If it is possible, how?
Thx

**Comment by chrissainty** [comment]
No this isn't possible, local storage is a browser feature and can't be accessed by anything except the browser as this would be a huge security flaw.

**Comment by djaus2** [comment]
Ok thx, as I thought.
