### ISSUE TITLE
Why when running on Chromium Edge the Block Third Party Cookies should be disabled 

### ISSUE THREAD

**Issue by dsapoznik** [Blazored/LocalStorage#112]
When running my Blazor Server side application in Chrome, the third party cookies  can be either enabled or disabled and the localStorgae works fine, however on Chromium Edge I get the following error:

Exception: 
Microsoft.JSInterop.JSException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

I thought that cookies are not related with localStorage.  

What should I do to make it to work on Chromium Edge ?   Should I need to tell our users to disable the Block Third Party Cookies.

**Comment by chrissainty** [comment]
Hi @dsapoznik, cookies don't have anything to do with Local Storage. I've not seen anyone have this error message before. I would suggest that you have some kind of local issue which is producing this problem. I'm not sure I can give you much advice on this one I'm afraid.
