### ISSUE TITLE
Syntax to Read Multiple Values

### ISSUE THREAD

**Issue by mysteryx93** [Blazored/LocalStorage#113]
What approach should we take to read multiple values?

- I can call GetItemAsync sequentially (probably the slowest)
- I can create multiple tasks and run with Task.WhenAll
- I can create a class containing both properties (probably best when reading many values at once)

Will it be doing a client round-trip on each call or will it cache the value?

For setting values I can "set it and forget it" so I can set both values at the same time. Will this cause any concurrency issue in writing the data?

I think this should be documented as part of the basic usage.

Also, why are you using ValueTask for async methods? If it's relying on caching and running quickly the second time, it makes sense. If it's querying the client on every call, then Task would be better.

**Comment by chrissainty** [comment]
Hi @mysteryx93,

> What approach should we take to read multiple values?

It depends on what your app is doing, I always do the simplest and easiest to maintain option first and only add in more complexity when needed. So I would start by looping over to get values, if you notice a problem at any point with that then try something different to mitigate it. 

> Will it be doing a client round-trip on each call or will it cache the value?

I'm assuming from this that you're using Blazor Server. The answer is yes, it will always go to the client as that is where local storage is. 

> For setting values I can "set it and forget it" so I can set both values at the same time. Will this cause any concurrency issue in writing the data?

I don't understand this question I'm afraid. 

> I think this should be documented as part of the basic usage.

What should? Again, I don't understand what you're referring to here.

**Comment by mysteryx93** [comment]
OK so each call requires a roundtrip to the server, which can mean 100-200ms per call. Reading 5 properties in a row could bring a delay of up to 1 second. I think the best approach for reading 2 properties is to create 2 tasks in parallel. For 10 properties, combining them into a single object would be better.

Since the Get and Set methods are doing a roundtrip to the server, I think they should return Task instead of ValueTask. ValueTask is an optimization for when the method is likely to be synchronous, which is not the case here because it needs to query over the internet.

**Comment by chrissainty** [comment]
Thanks for sharing your opinion. We won't be changing to task we'll be staying with ValueTask. The Blazor JS interop APIs return ValueTasks as when using it with Blazor Wasm calls can be made synchronously.
