### ISSUE TITLE
[Feature Request] Support for Cookies

### ISSUE THREAD

**Issue by mysteryx93** [Blazored/LocalStorage#114]
Supporting Local Storage or Cookies in Blazor is pretty much the same: it requires JS interop.

I think the simplest way of supporting cookies is to add it to this library that already does the hard work.

Would you consider adding support for cookies? This would be useful for storing security tokens such as login info that is not safe to store in Local Storage. You could also put a warning that Local Storage is not safe for sensitive data because any embedded JavaScript from other sources can access the data.

**Comment by chrissainty** [comment]
Thanks for raising this issue. This isn't something we'd look to support. This library is for local storage, cookies are out of scope.
