### ISSUE TITLE
[Bug] Nested List

### ISSUE THREAD

**Issue by Kylar182** [Blazored/LocalStorage#115]
**Describe the bug**
I have a Nested List of Objects within an Object that I save in Local Storage. I can look and see that it saves fine. When retrieving it however, the list doesn't come with the Object. 

**To Reproduce**
1. Add Object with Sub List
2. Retrieve Object with Sub List

**Expected behavior**
Working or Work around

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by Kylar182** [comment]
On further Checking, the list is private set and I believe that might be an issue with JSON serialization itself. Please let me know

**Comment by chrissainty** [comment]
Hi @Kylar182 - Yes this is a limitation with the JSON serialization. It is fixed in .NET 5 but we've not upgraded the library yet. I'm hoping to get it done in the next week.

**Comment by SimonCropp** [comment]
> It is fixed in .NET 5  

So i assume this is fixed by https://github.com/Blazored/LocalStorage/pull/117

**Comment by Kylar182** [comment]
> > It is fixed in .NET 5
> 
> So i assume this is fixed by #117

The PR for 117 wasn't accepted according to what I'm looking at

**Comment by SimonCropp** [comment]
@Kylar182 

> The PR for 117 wasn't accepted according to what I'm looking at

yep. just linking the issue to the PR
