### ISSUE TITLE
Need secured (encrypted) data to be stored into browser localstorage

### ISSUE THREAD

**Issue by frozt86** [Blazored/LocalStorage#118]
Maybe it need some featured functions to store secured (encrypted) data into browser local storage using AES (or RSA).

**Comment by chrissainty** [comment]
Thanks for opening this issue @frozt86. Could I ask what you want to store in Local Storage?

The reason I ask is if it's sensitive it should be stored on the server and not the client. At best, local encryption is going to slow someone down. Obviously, if you're just trying to put people off and what you're storing isn't sensitive then that might be fine.

**Comment by frozt86** [comment]
it's right to store some sensitive data on the server. But somehow with blazor WASM it need store some sensitive data (not all of it) in localstorage like userID, userAccesLevelID or else. something like that.

yes it's very simple way that i could done it. I just want to put my tought here.

**Comment by frozt86** [comment]
I just find out that System.Security.Cryptography.Algorithms is not supported on .Net WASM. so i will close this Issue because it cannot be done (for now).
