### ISSUE TITLE
metadata bag with each entry

### ISSUE THREAD

**Issue by SimonCropp** [Blazored/LocalStorage#121]
i think it would be useful to have a dictionary bag that is stored with each entry. this gives people the ability to store metadata associated the poco. it also give you the opportunity to store two important pieces of info. 

 * the version of the local storage lib
 * the version of the assembly the entry comes from

both these versions are very useful if ever a breaking change needs to be made to either the local storage lib or the poco lib. 

thoughts?

**Comment by chrissainty** [comment]
It's an interesting idea, Simon. Let me think it over and I'll come back to you.

**Comment by SimonCropp** [comment]
thoughts on this?
