### ISSUE TITLE
local storage data automatically  expire

### ISSUE THREAD

**Issue by LingDian2019** [Blazored/LocalStorage#125]
Expired data is automatically deleted. After the expiration of business scene data, it is necessary to actively request the server to obtain the latest data.thank you

**Comment by chrissainty** [comment]
Hi, I'm not sure what you're asking for here, could you please explain a bit more?

**Comment by LingDian2019** [comment]
Thank you for your reply,Blazor WebAssembly needs to hold the Token for 1 hour after login.When localStorage reaches 1 hour, localStorage will automatically remove the Token.Call SetItemAsync on localStorage and add an expiration time parameter

**Comment by chrissainty** [comment]
I think you're describing a scenario? But don't understand what it has to do with this library? Is this something you're trying to do?

**Comment by LingDian2019** [comment]
This business scenario has been implemented, but I wish I could support automatic data expiration like Redis, which feels more elegant

**Comment by chrissainty** [comment]
We have no way of automatically expiring information in local storage. I don't feel this is something this library should be responsible for anyway. Plus, this seems something that is reasonably easy to implement in application code where it can be tailored to what a particular application requires.
