### ISSUE TITLE
RemoveItemAsync

### ISSUE THREAD

**Issue by dkboon01** [Blazored/LocalStorage#126]
**Please be sure to check the readme file before raising an issue.**
Is there away to RemoveItemAsync so you can only delete one of the values in the key? Instead of deleting the entire key?
RemoveItemAsync(string key, T data)

**Comment by chrissainty** [comment]
I'm not sure what you mean by this @dkboon01? Local Storage is a key/value store. You can't have multiple values for a key.

**Comment by dkboon01** [comment]
Never mind I figured out what my issue was. Sorry, it works great...
