### ISSUE TITLE
Sign the assembly with a strong name key

### ISSUE THREAD

**Issue by pmachapman** [Blazored/LocalStorage#127]
**Is your feature request related to a problem? Please describe.**
If I reference this assembly from an assembly that is signed with strong name key file, I receive the following warning from the compiler:

`CS8002:	Referenced assembly 'Blazored.LocalStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

**Describe the solution you'd like**
The assembly needs to be signed with a strong name key file (see the Signing tab in the Project Properties dialog in Visual Studio) to resolve this warning for any signed projects that reference this library.

**Describe alternatives you've considered**
Unsigning my assembly. Not ideal, as it is best practice to sign .Net assemblies (see https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming)

**Additional context**
I am happy to create a pull request with this change (it is a straightforward change).

**Comment by chrissainty** [comment]
I'm unfamiliar with strong signing @pmachapman. I'm assuming this would require a certificate in order to sign? If this assumption is correct, I'm guessing these aren't free?

**Comment by pmachapman** [comment]
No certificate is required - the key is self-signed by the developer in Visual Studio, and can be included in the repo as it is only providing a unique identity for the package, not code security (like a code signing certificate). More details are available at https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named. No fees, etc are required.

I can create a pull request with the change, if you like?

**Comment by chrissainty** [comment]
That would be great, @pmachapman. I'm preparing the v4 release, it would be great to get this in there.

**Comment by pmachapman** [comment]
Excellent! I'll create the pull request tomorrow.

**Comment by chrissainty** [comment]
@pmachapman I have a quick question. In V4 we're taking a dependancy on bUnit which isn't a signed assembly. I've noticed this produces a warning on our build. Will also show as a warning on your build?

**Comment by pmachapman** [comment]
Yes I get the warning for the v4 branch - didn't think to test the v4 branch - d'oh!

Looks like it is an issue they are aware of since Feb: https://github.com/egil/bUnit/issues/316

**Comment by chrissainty** [comment]
@pmachapman I've asked where Egil is on this. If he isn't happy about signing bUnit, then I don't think there is much point in signing Blazored. We'll have to see what he comes back with.
