### ISSUE TITLE
[Feature Request] Save tuples into the localstorage

### ISSUE THREAD

**Issue by pinguinosod** [Blazored/LocalStorage#130]
**Is your feature request related to a problem? Please describe.**
I want to save tuples into the localstorage.
Currently If I do `localStorage.SetItem("tuple", ("hello", "world"));` I just get `{}` saved into the localstorage

**Describe the solution you'd like**
`localStorage.SetItem("tuple", ("hello", "world"));`
Could save `{"Item1":"hello","Item2":"world"}`

**Comment by chrissainty** [comment]
Hi @pinguinosod, this will be fixed when I release version 4. In .NET 5 `System.Text.Json` added field support which is what's needed to achieve this. The Issue and linked PR can be found https://github.com/dotnet/runtime/issues/876.
