### ISSUE TITLE
[Feature Request] Provide prereleases

### ISSUE THREAD

**Issue by LeonSpors** [Blazored/LocalStorage#137]
Can you provide a prerelease for the current and the upcoming previews? I ran the upgrade by myself and your tests pass. I think there should not be any problem.

**Comment by chrissainty** [comment]
I'd love to get this setup. I just need to figure out how to automate it with Actions when I get some time.

**Comment by chrissainty** [comment]
I'm closing this as there isn't anything to do here, but I will try and remember to publish pre-releases going forward.
