### ISSUE TITLE
[Bug] LocalStorageService inaccessable V4

### ISSUE THREAD

**Issue by Kylar182** [Blazored/LocalStorage#138]
**Describe the bug**
In V3 you allowed us to register LocalStorageService as a singleton. This is needed for some of my other state management services. In V4 you no longer allow this.

AddSingleton<ILocalStorageService, LocalStorageService>();

**To Reproduce**
AddSingleton<ILocalStorageService, LocalStorageService>();

"internal class LocalStorageService : ILocalStorageService, ISyncLocalStorageService"

**Expected behavior**
Allow usage for Singleton Register

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Additional context**
Pretty please?

**Comment by chrissainty** [comment]
Hi @Kylar182. Are these state management services things you've written? If not which packages are you using? 

As singleton and scoped behave the same in Blazor WebAssembly, it would be better to switch your state services to scoped. I'm very reluctant to swap the `LocalStorageService` to public as, due to some redesign, it would mean I have to expose some implementation details which I really don't want to.

**Comment by Kylar182** [comment]
> Have you tried changing your services to scoped? As I mentioned in my last comment. Scoped and Singleton are the same in Blazor WebAssembly.

How are they the same? Also, I'm building a Blazor Desktop App this fall and it would be nice to share code. Again, I can stick to V3 for now or Fork it if you're insistent.

**Comment by chrissainty** [comment]
Scoped services live for the life of the request, singleton for the life of the app. As a Blazor Wasm app lives and dies in the browser instance the two scopes are the same. There is no request to scope a service to. This is documented in the [official docs](https://docs.microsoft.com/en-gb/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-5.0&pivots=webassembly#service-lifetime). 

If you want to keep you services as singleton then you will need to stick with v3. But changing to scoped will give the same behaviour and you'll be able to upgrade, it's up to you.

**Comment by Kylar182** [comment]
"As a Blazor Wasm app lives and dies in the browser instance the two scopes are the same", unless the user refreshes the page, hits an error and clicks reload, etc. etc. etc.

https://chrissainty.com/service-lifetimes-in-blazor/
