### ISSUE TITLE
[Question] Upgrade from 3.0.0 to 4.0.0

### ISSUE THREAD

**Issue by jolubar** [Blazored/LocalStorage#139]
After upgrade package to version 4.0.0 I get this message

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Blazored.LocalStorage from 4.0.0 to 3.0.0. Reference the package directly from the project to select a different version. 
 Web.Server -> Web.Client -> Blazored.LocalStorage (>= 4.0.0) 

Please help!

**Comment by chrissainty** [comment]
Could you provide the step to repro the issue or link to a repo with a project which shows the issue. Once you do that I can investigate.

**Comment by AMTraxTGE** [comment]
I believe I am also having this same issue. I'm using the preview version of **.net6.0 (6.0.100-preview.3.21202.5)**. I attempted to install `LocalStorage v4.0.0` using NuGet Package Manager.

Framework in csproj:
```csproj
<TargetFramework>net6.0</TargetFramework>
```
After Install Attempt:
![image](https://user-images.githubusercontent.com/12130422/118126938-02192c00-b3c7-11eb-8c37-220781318a52.png)

If I use the previous version of LocalStorage (v3.0.0), these errors do not occur.

### Steps to Reproduce:

1. Create/Open a Blazor-Server application in Visual Studio using Target Framework `.NET 6.0 (Preview)`
2. Attempt to install LocalStorage v4.0.0 via NuGet Package Manager

**Expected:**
- Installation of LocalStorage v4.0.0

**Actual:**
```
Error	NU1605	Detected package downgrade: Microsoft.AspNetCore.Components.Web from 6.0.0-preview.3.21201.13 to 5.0.5. Reference the package directly from the project to select a different version. 
 Otis.Presentation -> Blazored.LocalStorage 4.0.0 -> bunit.core 1.1.5 -> Microsoft.AspNetCore.Components.Web (>= 6.0.0-preview.3.21201.13) 
 Otis.Presentation -> Blazored.LocalStorage 4.0.0 -> Microsoft.AspNetCore.Components.Web (>= 5.0.5)

Error	NU1605	Detected package downgrade: Microsoft.AspNetCore.Components from 6.0.0-preview.3.21201.13 to 5.0.5. Reference the package directly from the project to select a different version. 
 Otis.Presentation -> Blazored.LocalStorage 4.0.0 -> bunit.core 1.1.5 -> Microsoft.AspNetCore.Components (>= 6.0.0-preview.3.21201.13) 
 Otis.Presentation -> Blazored.LocalStorage 4.0.0 -> Microsoft.AspNetCore.Components (>= 5.0.5)

```

**Comment by chrissainty** [comment]
Have you tried installing the package versions you need directly as the error message suggests?

```
Reference the package directly from the project to select a different version. 
```

**Comment by AMTraxTGE** [comment]
Yes, this does work. I'm able to install after I install the preview version of ` Microsoft.AspNetCore.Components.Web`

I would assume this happened from `bunit.core 1.1.5` using the preview version.

@jolubar would need to add `Blazored.LocalStorage (>= 4.0.0)` to the project manually or update it somewhere else that is using version 3.0.0 still first.

**Comment by chrissainty** [comment]
This should be resolved with the latest release which separates Blazored.LocalStorage and Blazored.LocalStorage.TestExtensions
