### ISSUE TITLE
4.0.0 SetItemAsync can no longer store raw string

### ISSUE THREAD

**Issue by groogiam** [Blazored/LocalStorage#140]
**Describe the bug**
It appears there is an undocumented breaking change in 4.0.0 to the SetItemAsync function. In 3.0 you could pass a string directly to this method and it would be stored without being json encoded.

**To Reproduce**

This snippet demostrates the issue

```c#
var userRolesJson = await _http.GetStringAsync("api/UserProfile/MySecurityProfile");

//in 3.0 this would store a non json encoded string
//in 4.0 the string is encoded breaking the GetItemAsync statement below that previously worked
await _localStorage.SetItemAsync(SecurityProfileLocalStorageKey, userRolesJson);

//broken in 4.0 worked previously in 3.0
var myProfilePoco = await _localStorage.GetItemAsync<UserSecurityProfile>(SecurityProfileLocalStorageKey);
```

Looks like the removal of the following statement on line 33 in LocalStorageService.cs in commit 76dbf13f is what caused this behavior

```c#
if (data is string)
{
    await _jSRuntime.InvokeVoidAsync("localStorage.setItem", key, data).ConfigureAwait(false);
}
```

**Expected behavior**
Expected behavior would be the interface preserves it existing semantic; e.g the ability to store a non json encoded string.

If the change to the existing semantic was intended then documenting it as a breaking change from 3.0 to 4.0 would probably help avoid further issues being opened on this topic.

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by teland94** [comment]
+1 same issue. I would to like store simple strings. Now I get a string with quotas.

**Comment by chrissainty** [comment]
Thank you for spotting this @groogiam. You're correct this is an undocumented breaking change. I will update the readme with this.

**Comment by groogiam** [comment]
Any thoughts on potentially adding additional calls to the api to allow for storing and retrieving un-encoded json strings? This seems like it might be useful to some folks.

**Comment by chrissainty** [comment]
Yes, definitely but just playing devils advocate for a second. Why does it matter if the library serialises a string if it also takes care of deserialising it on the way out? You don't have to do any extra work, it's all taken care of for you.

**Comment by groogiam** [comment]
The use case that caused this issue in my code was a rest call that returned raw json and did not serialize it directly to a poco. Before I could just write it to local storage now I have to serialize it from the httpclient to a poco just to have the component reserialize it for storage.

Another use case I was thinking of there was some external javascript component outside blazor that may have to access a string created with this component local storage. The consuming js would then have the extra step of having to deserialize the string.

All of this can be overcome with one extra manual serialization or deserialization but having the flexibility for some of these more  unique cases seems like it could be useful.

**Comment by chrissainty** [comment]
I agree @groogiam. What I think would be the best solution here is to add an additional method to `ILocalStorageService`, something like this:

```csharp
ValueTask SetItemAsStringAsync(string key, string data);
```

This would then give us a nice paring with `GetItemAsStringAsync`. 

Once this was done developers can choose to either have the library handle serialization by using `SetItemAsync` and `GetItemAsync`. Or handle serialization themselves by using `SetItemAsStringAsync` and `GetItemAsStringAsync`.

How does that sound to you?

**Comment by groogiam** [comment]
Sounds perfect!

**Comment by chrissainty** [comment]
@groogiam I've just pushed a new version of the package with the new methods in it. Let me know if you find any issues.

**Comment by groogiam** [comment]
Just integrated it into my code and it appears to be working without issue. Thanks for all your help and all your great work on this project!
