### ISSUE TITLE
[Question] How to inject an ILocalStorageService in a custom ILoggerProvider?

### ISSUE THREAD

**Issue by MicBe** [Blazored/LocalStorage#143]
Hello!

I want to create a logger that logs in local storage. I want to inject ILocalStorageService into my custom ILoggerProvider constructor:

`public MyCustomLoggerProvider(ILocalStorageService localStorageService)`

At runtime, I get the following error:

> Cannot consume scoped service 'Blazored.LocalStorage.ILocalStorageService' from singleton 'Microsoft.Extensions.Logging.ILoggerProvider'

I know that ILocalStorageService is a scoped service but ILoggerProvider is a singleton, and I cannot change that to Scoped. So I tried to create ILocalStorageService as a singleton:
`builder.Services.AddSingleton<ILocalStorageService, LocalStorageService>();`

But I get: 

> 'LocalStorageService' is inaccessible due to its protection level

Is there a reasonable workaround for this? I am new to asp.net core and Blazor WebAssembly.

Thanks

**Comment by chrissainty** [comment]
Hi @MicBe, how have you setup your logger?

**Comment by MicBe** [comment]
Hi Chris,

Thanks for your answer.

I have created an extension method like the following to instantiate the LocalStorageLoggerProvider:
ClientLoggerExtensions.cs:
```
public static ILoggingBuilder AddLocalStorageLogger(this ILoggingBuilder builder)
{
    builder.AddConfiguration();

    builder.Services.TryAddEnumerable(
        ServiceDescriptor.Singleton<ILoggerProvider, LocalStorageLoggerProvider>());
    LoggerProviderOptions.RegisterProviderOptions<ClientLoggerOptions, LocalStorageLoggerProvider>(builder.Services);

    return builder;
}

```
LocalStorageLoggerProvider.cs (simplified):
```
public class LocalStorageLoggerProvider : ILoggerProvider
{
    private ConcurrentDictionary<string, LocalStorageLogger> loggers = new();

    private readonly ILocalStorageService localStorage;

    public LocalStorageLoggerProvider(ILocalStorageService _localStorage)
    {
        localStorage = _localStorage;
    }

    public ILogger CreateLogger(string categoryName)
    {
        var logger = new LocalStorageLogger(categoryName, localStorage);
        return loggers.GetOrAdd(categoryName, logger);
    }

    public void Dispose()
    {
        loggers.Clear();
    }
}
```

The logger itself (simplified):
LocalStorageLoggerProvider.cs
```
public class LocalStorageLogger : ILogger
{
    private string category;
    private readonly ILocalStorageService localStorage;

    public LocalStorageLogger(string _category, ILocalStorageService _localStorage)
    {
        category = _category;
        localStorage = _localStorage;
    }
    public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
    {
        if (!IsEnabled(logLevel))
            return;

        // TODO: Call localStorage to fill local storage
    }

    public bool IsEnabled(LogLevel _logLevel) => true;

    public IDisposable BeginScope<TState>(TState state) => default;
}
```

And in Program.cs, I have those two consecutive lines:
```
builder.Services.AddBlazoredLocalStorage();
builder.Logging.AddLocalStorageLogger();
```

I hope that answers your question.

**Comment by chrissainty** [comment]
Could you not register you logging provider as scoped by updating this line:

```csharp
builder.Services.TryAddEnumerable(ServiceDescriptor.Scoped<ILoggerProvider, LocalStorageLoggerProvider>());
```

**Comment by MicBe** [comment]
I tried it, but then I get that error at runtime:
`System.InvalidOperationException: Cannot consume scoped service 'Microsoft.Extensions.Logging.ILoggerProvider' from singleton 'Microsoft.Extensions.Logging.ILoggerFactory'.`

**Comment by chrissainty** [comment]
I found this issue which directly relates to your problem. https://github.com/dotnet/aspnetcore/issues/20938#issuecomment-615124250

There is a suggestion there about a way round this. The other option is you take a copy of the LocalStorageService from this repo and add it to your project. You can then register it yourself as a singleton.

**Comment by MicBe** [comment]
I also tried that option but then I get this error when calling GetRequiredService<ILocalStorageService>():
`System.ArgumentNullException: Value cannot be null. (Parameter 'provider')`

I think I will resort to the last option of copying the file LocalStorageService in my project. Won't there be any conflict with the file in the nuget package if I do this?

Thanks

**Comment by chrissainty** [comment]
You'll need to register the service yourself, instead of using the AddBlazoredLocalStorage() helper. Then you can make sure you use your version and not the one in the NuGet package. Something like this:

```
builder.Services.AddSingleton<ILocalStorageService, YourLocalStorageService>();
```

**Comment by MicBe** [comment]
I will try this, thank you!

**Comment by MicBe** [comment]
I copied the LocalStorageService.cs file in my project, but it won't compile because it depends on IStorageProvider and that class is internal.. I think I will have to fork the project and make the modifications, unless there is a simpler solution?

**Comment by MicBe** [comment]
I ended up adding those files manually in my project:
```
SystemTextJsonSerializer.cs
BrowserStorageProvider.cs
IStorageProvider.cs
LocalStorageService.cs
```

And in my Program.cs:
```
builder.Services.AddSingleton<IJsonSerializer, SystemTextJsonSerializer>();
builder.Services.AddSingleton<IStorageProvider, BrowserStorageProvider>();
builder.Services.AddSingleton<ILocalStorageService, LocalStorageService>();
builder.Services.AddSingleton<ISyncLocalStorageService, LocalStorageService>()
    .Configure<LocalStorageOptions>(configureOptions =>
    {
        configureOptions.JsonSerializerOptions.Converters.Add(new TimespanJsonConverter());
    });
```

But I am still wondering, if Scoped and Singleton are the same in Blazor WASM, why not register those services as singleton in the first place? A singleton can be consumed by any service scope, but a scoped service cannot be consumed by a singleton. So why keep this restriction?

**Comment by chrissainty** [comment]
Because this library needs to work with both Blazor WebAssembly AND Blazor Server. If I registered the services as Singleton, then a Blazor Server users wouldn't be able to use the library as it would cause some very odd behaviour at best and a big security issue at worse.

I'm glad you've found a resolution to your issue. In the future, I may add an additional extension method--specifically for Blazor WebAssembly--which allows developers with scenarios like yours the ability to register the services as Singleton. As you have a resolution now, I'm going to close this issue.
