### ISSUE TITLE
Cannot use it from a singleton

### ISSUE THREAD

**Issue by ABIOLI-COM** [Blazored/LocalStorage#145]
If you try to use it injecting it in a singleton, registered as:
    .AddSingleton<IXXX, XXX>()

it returns the error:

Unhandled exception rendering component: Cannot consume scoped service 'Blazored.LocalStorage.ILocalStorageService' from singleton 'xxx'.

**Comment by chrissainty** [comment]
Yep, that's because the service needs to be registered as scoped. If you're using Blazor WebAssembly then scoped and singleton behave the same. If you're on Blazor Server you shouldn't be using Singleton anyway.

**Comment by ABIOLI-COM** [comment]
Right. Nice explanation, thank you very much! :-)
