### ISSUE TITLE
[Bug] Compiler Error CS1061

### ISSUE THREAD

**Issue by cloudhal** [Blazored/LocalStorage#147]
The readme (for WASM) just says to add builder.Services.AddBlazoredLocalStorage();.
however that will result in error CS1061 unless using Blazored.LocalStorage; is also added to program.cs.

Not sure why this is not mentioned in the readme.

**Comment by chrissainty** [comment]
Now-a-days the IDE's, even VS Code, will highlight and even prompt developers to add using statements. I use Rider a lot and it often just adds them automatically. Hence it doesn't get put in every example. I'm going to close this as this isn't a bug with the package.
