### ISSUE TITLE
Add support for .NET 6

### ISSUE THREAD

**Issue by jawaidakhter** [Blazored/LocalStorage#148]
Unable to install package in blazor asp.net core 6

**Comment by chrissainty** [comment]
Yep, the package doesn't currently target .NET6. This is something we'll add closer to November.

**Comment by cyberdarius** [comment]
Due to this unresolved bug
https://github.com/dotnet/aspnetcore/issues/33559

That forced to update all wasm application to the latest .NET6 previews,

It would be nice if the package (maybe the preview) could target the latest .NET6

Thanks

**Comment by Alerinos** [comment]
Also please for updates, I'm using VS 2022 and it forces me and core 6 projects.

**Comment by IbrahimHabibeh** [comment]
For those of you who are still waiting for the update, I suggest utilizing Javascript interop to store data in local storage and change it later when this project is updated.

**Comment by chrissainty** [comment]
Apologies for the delay on this one but as soon as the RC is released I'll get the package updated. Which should be in the next two weeks.

**Comment by sshquack** [comment]
Thanks for creating blazored! Any estimate on when we might see a dotnet 6 support on nuget for all Blazored components?

**Comment by chrissainty** [comment]
It will be here before Christmas. Its been a really busy last half of the year but after next week things will start to quite down and all the Blazored packages will get some much deserved TLC. I appreciate the patience.

**Comment by EnesKartal** [comment]
any update ? Still not working on .net 6

**Comment by Graynoble** [comment]
I am also very interested in this for .net 6!!! Anxiously awaiting the Program.cs code :) :) :)

**Comment by chrissainty** [comment]
@EnesKartal A .NET 6 version of the package was released in February.

**Comment by RSMs007** [comment]
I'm use VS2022 with .Net6 last update  of Blazored LocalStorage ver 4.2.0 don't install
