### ISSUE TITLE
Question about Server side use of local storage

### ISSUE THREAD

**Issue by MarkStega** [Blazored/LocalStorage#15]
I have cloned the Blazored.Gitter repo and am trying to consolidate the SCSS. In trying to run the server side version of the project I receive an error from LocalStorage after entering my API key. It occurs on the source line of `await LocalStorage.SetItem("GitterKey", apiKey);`

`[2019-04-30T13:56:20.554Z] Error: Microsoft.JSInterop.JSException: Could not find 'Blazored' in 'window'.
d/<@http://localhost:50870/_framework/blazor.server.js:8:20878
d@http://localhost:50870/_framework/blazor.server.js:8:20839
beginInvokeJSFromDotNet/r<@http://localhost:50870/_framework/blazor.server.js:8:21429
beginInvokeJSFromDotNet@http://localhost:50870/_framework/blazor.server.js:8:21403
x</e.prototype.invokeClientMethod/<@http://localhost:50870/_framework/blazor.server.js:1:16651
x</e.prototype.invokeClientMethod@http://localhost:50870/_framework/blazor.server.js:1:16622
x</e.prototype.processIncomingData@http://localhost:50870/_framework/blazor.server.js:1:14619
e/this.connection.onreceive@http://localhost:50870/_framework/blazor.server.js:1:11163
N</e.prototype.connect/</</</i.onmessage@http://localhost:50870/_framework/blazor.server.js:1:30452

   at Blazored.LocalStorage.LocalStorageService.GetItem[T](String key)

   at Blazored.LocalStorage.LocalStorageService.RaiseOnChangingAsync(String key, Object data)

   at Blazored.LocalStorage.LocalStorageService.SetItem(String key, Object data)

   at Blazor.Gitter.Core.Components.Shared.AppState.SaveApiKey() in C:\Solutions\TemporarySolutions\Gitter\src\Blazor.Gitter.Core\Components\Shared\AppState.cs:line 115

   at Blazor.Gitter.Core.Components.Pages.IndexModel.SignIn(Boolean remember) in C:\Solutions\TemporarySolutions\Gitter\src\Blazor.Gitter.Core\Components\Pages\Index.razor.cs:line 44

   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)

   at Microsoft.AspNetCore.Components.Rendering.Renderer.GetErrorHandledTask(Task taskToHandle) blazor.server.js:15:27350
    log http://localhost:50870/_framework/blazor.server.js:15
    b http://localhost:50870/_framework/blazor.server.js:8
    v http://localhost:50870/_framework/blazor.server.js:8
    invokeClientMethod http://localhost:50870/_framework/blazor.server.js:1
    invokeClientMethod http://localhost:50870/_framework/blazor.server.js:1
    processIncomingData http://localhost:50870/_framework/blazor.server.js:1
    onreceive http://localhost:50870/_framework/blazor.server.js:1
    onmessage http://localhost:50870/_framework/blazor.server.js:1
[2019-04-30T13:56:20.555Z] Information: Connection disconnected. blazor.server.js:1:5137
`

**Comment by chrissainty** [comment]
I doubt the JS is being included due to the static asset importing issue with server-side Blazor. You would either have to include a copy of the JS manually or use [MisterMagoos library](https://github.com/SQL-MisterMagoo/BlazorEmbedLibrary) I reference on in the readme,

**Comment by MarkStega** [comment]
Chris,

According to the trace from the library the JS is being included; You can check it out in the pending PR in the BalzoredGitter repository.

**Comment by chrissainty** [comment]
Umm, weird. I’ll check out the PR branch in the morning and see if I can
spot anything.

**Comment by chrissainty** [comment]
By the looks of it @MarkStega, no CSS of JS in being included. I've cloned your branch and when I run the server-side app I get the following:

![blazored-gitter](https://user-images.githubusercontent.com/6171719/57061973-c5ce7380-6cb6-11e9-96ca-982e70a411de.png)

**Comment by MarkStega** [comment]
Chris,
I think your assessment is correct but I don't understand why the embed library trace seems to indicate that the files were included. In implementing PR#38 @sql-mistermagoo moved the embed library call to app.razor/app.razor.cs and when I merged the PR everything worked.

**Comment by SQL-MisterMagoo** [comment]
It was just a problem with lifecycle events and moving the embed to App made sure it happens early in the lifecycle.

**Comment by SQL-MisterMagoo** [comment]
I can't wait until they provide a proper fix for this

**Comment by MarkStega** [comment]
Agreed; But at least you have provided a reasonable work-around...

**Comment by longhornleads** [comment]
Does anyone have an example project for using local storage in a blazor server-side application.  I know this says to copy the javascript files but an example would be really helpful.  Thanks!
