### ISSUE TITLE
Is it possible to use LocalStorage in a DelegatingHandler?

### ISSUE THREAD

**Issue by redowl5** [Blazored/LocalStorage#151]
We have a server side Blazor project and looking to add JWT tokens (which are being saved using LocalStorage on login) to all httpclient requests by using a delegatingHandler.  

The delegating handler includes the line

var savedToken =  await _myLocalStorageService.GetItemAsync("jwt");

where _myLocalStorageService has the constructor

public MyLocalStorageService(ILocalStorageService storage)

Regardless of when the delegating handler gets called, we get the "JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. " when calling GetItemAsStringAsync

Any ideas?

Thanks

**Comment by chrissainty** [comment]
No idea on this one. Could you provide a minimal working repro of the issue and I can take a look.

**Comment by chrissainty** [comment]
I'm going to close this in favour of #156
