### ISSUE TITLE
[Bug] Loading large object causes Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.

### ISSUE THREAD

**Issue by Mr-Technician** [Blazored/LocalStorage#153]
**Describe the bug**
When loading a large object from localstorage, the error above appears in the console and the connection to the site is briefly dropped before reconnecting.

**To Reproduce**
Save a complex json object to local storage and attempt to read it. Assuming the returned message is > 32 KB, the blazor app will disconnect the circuit.

**Expected behavior**
Presumably, this is caused by the signalr message size limitation. I would expect Blazor.LocalStorage to split the json into multiple chunks and send them separately.

**Screenshots**
![image](https://user-images.githubusercontent.com/26885142/123703307-d2fd3380-d829-11eb-8f73-8f96cafdeee6.png)
Below you can see the 33KB message that causes the site to break:
![image](https://user-images.githubusercontent.com/26885142/123703395-ee683e80-d829-11eb-9873-318a43e352fa.png)

**Hosting Model:**
 - Blazor Server

Is this something that should be handled by the library or am I out of luck? I'd rather not increase the signalr message size unless I need to.

**Comment by chrissainty** [comment]
Unfortunately this isn't something the library can handle. There is no way for us to tell if the app is a Blazor Server or WebAssembly application. Managing the SignalR connection is handled by the framework and we have no access to it. I think the only option here is for you to increase the message size.
