### ISSUE TITLE
Chrome incognito mode no access to localstorage. (Inside of an iFrame)  [Bug]

### ISSUE THREAD

**Issue by devreepiet** [Blazored/LocalStorage#160]
The bug appears when using a blazor site in incognito mode when it is inside of an iFrame. 
It breaks the site when accessing the service.
(Incoginto mode is not necessary, just the 3d party cookies need to be blocked).

1. Create a standard blazor site
2. Add Blazored/LocalStorage
3. Access the service on a button click
4. Create a new html page with an iFrame with the source url of  the new blazor project

**Expected behavior**
Following error message is thrown. 
blazor.webassembly.js:1 Microsoft.JSInterop.JSException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

**Screenshots**
![image](https://user-images.githubusercontent.com/78440527/130409789-afb8d5b2-f323-4915-a4d8-072d89d066d0.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly
 - Blazor page inside of an iFrame

**Comment by chrissainty** [comment]
I don't think this a bug, I don't think what you're attempting is allowed, hence the error you're getting. An iFrame is a different origin to the hosting application hence they both have their own local storage instances. Once isn't allowed to access the other as it would be a security breach.
