### ISSUE TITLE
[Bug] There is no registered service of type 'Blazored.LocalStorage.ILocalStorageService' or 'LocalStorageService' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by PilipenkoAB** [Blazored/LocalStorage#165]
Trying to unit-test .razor with bUnit and Mock the page (@inject ILocalStorageService _localStorage) with test as follows:

[Fact]
public void Test()
{
using var ctx = new TestContext();
ctx.Services.AddBlazoredLocalStorage();
...
...
}

Having an error:
System.InvalidOperationException : Cannot provide a value for property '_localStorage' on type 'App.Components.Index'. There is no registered service of type 'Blazored.LocalStorage.ILocalStorageService'.

if trying to use 
    ctx.Services.AddScoped<ILocalStorageService, LocalStorageService>();
or
    ctx.Services.AddSingleton<ILocalStorageService, LocalStorageService>();

Having a compiler error:
Error	CS0122	'LocalStorageService' is inaccessible due to its protection level

Looks like the same issue as https://github.com/Blazored/LocalStorage/issues/61#issuecomment-867189222_

**Comment by chrissainty** [comment]
Can you share a minimum repo of the issue please? Then I can look into it.

**Comment by PilipenkoAB** [comment]
I'm sorry, the problem was solved by itself. With some unknown magic ctx.Services.AddBlazoredLocalStorage();  just started to work without any problems next day. I guess it was a problem of cache or something like that.
