### ISSUE TITLE
[Question] Repository service using localstorage not 'ready'

### ISSUE THREAD

**Issue by MathieuDR** [Blazored/LocalStorage#166]
**Please be sure to check the readme file before raising an issue.**
When I'm trying to create a repository using the localstorage package, the `ILocalStorageService` is not ready in my 'OnInitializedAsync' method.

When I inject `ILocalStorageService` directly in the page, it behaves as expected.

Is there a solution/example that I can use for this usecase?

**Comment by chrissainty** [comment]
Could you provide some code showing what you're trying to do?

**Comment by MathieuDR** [comment]
> Could you provide some code showing what you're trying to do?

Sure!

I'll walk you through the sample from LocalStorage itself that I changed a bit. But before I would like to say that if I just run the sample as is, it's working as expected.

[The razor page](https://github.com/MathieuDR/ResourceCalculator/blob/main/BlazorApp/Pages/Index.razor): This page has the 'example' code. On the initialization the first call to the local storage will return null. It doesn't matter which one you put first. In this case I changed them around to test.

- `GetStringFromLocalStorage`: Returns null
- `GetNameFromLocalStorage`: Returns a value

[The service & repo](https://github.com/MathieuDR/ResourceCalculator/blob/main/BlazorApp/StupidService.cs) A sample service and repo, just to demonstrate. I use the DI to inject `ILocalStorageService `.

[Program.cs](https://github.com/MathieuDR/ResourceCalculator/blob/main/BlazorApp/Program.cs) For the DI.

[The whole Git repository](https://github.com/MathieuDR/ResourceCalculator)

**Comment by chrissainty** [comment]
Honestly, I'm not sure why this is happening. As the sample works I'd suggest it's something to do with your respoitory implementation. But this might be a question for the .NET team as it might be an issue with DI.

I'm sorry I can't be more help on this one.

**Comment by MathieuDR** [comment]
> Honestly, I'm not sure why this is happening. As the sample works I'd suggest it's something to do with your respoitory implementation. But this might be a question for the .NET team as it might be an issue with DI.
> 
> I'm sorry I can't be more help on this one.

Ok, thanks.

I assume that it gets created before the page gets created and because of that the LocalStorageService JSInterop isn't ready yet.

Not sure how I would handle this, But i'll close this ticket

**Comment by MathieuDR** [comment]
For later reference, using the sync version resolves this issue.
