### ISSUE TITLE
[Question]After updating to v4.2.0 I get a JSException in SetItemAsString

### ISSUE THREAD

**Issue by Martin521** [Blazored/LocalStorage#172]
Since I updated to 4.2.0, I get `Microsoft.JSInterop.JSException: Invalid JS call result type '3'` in a call to SetItemAsString (with a valid string).

When I roll back to 4.1.5, the problem is gone.

So, before I try to create a minimal example and file a bug report, I wanted to ask if there is anything obvious that was changed in 4.2.0 that could cause the exception.

**Comment by Martin521** [comment]
I found a workaround [here](https://github.com/fsbolero/Bolero/issues/250#issuecomment-1028945933). Seems to be a Blazor or SDK issue. Nevertheless, it appears for me only for 4.2.0, not for 4.1.5.

**Comment by chrissainty** [comment]
I'm going to close this as it appears to be an isolated problem. I can't seem to repro it either.
