### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by franky1017** [Blazored/LocalStorage#173]
When saving values to local storage, regardless of data type, it saves as the value itself without any quotation mark. For example boolean will be saved as True/False and MyValue will just be the MyValue.

However, occasionally, no pattern or reproducible steps, it will add double quotes to the value. True will become "True", MyValue will become "MyValue".

This caused a problem when retrieving them as "True" can no longer be converted to boolean and "MyValue" comes back with the quotes as parts of the value.

Unfortunately, I am not able to reproduce consistently, for now, I will just have to manually remove them if found during the GetItemAsStringAsync() method.

**Comment by chrissainty** [comment]
It sounds to me like you've been using a mix of `SetItemAsStringAsync` and `SetItemASync`. This would explain the quote being there on some occasions and not others.

**Comment by franky1017** [comment]
Aha, that explains it! Thanks Chris :-)
