### ISSUE TITLE
Nuget Package is Not Update

### ISSUE THREAD

**Issue by HossienMehdikhah** [Blazored/LocalStorage#185]
Hi,
I Wants To Use extension Method  AddBlazoredLocalStorageAsSingleton 
but its not exist in package

**Comment by chrissainty** [comment]
Hi @HossienMehdikhah,

This feature is currently in the latest preview package

**Comment by HossienMehdikhah** [comment]
@chrissainty  And I must Download Source For Use Preview Relase?

**Comment by chrissainty** [comment]
No, you just need to install the preview version of the package from NuGet:

https://www.nuget.org/packages/Blazored.LocalStorage/4.3.0-preview.1
