### ISSUE TITLE
AddBlazoredLocalStorageAsSingleton not found

### ISSUE THREAD

**Issue by josegerar** [Blazored/LocalStorage#190]
**AddBlazoredLocalStorageAsSingleton not found**

**Comment by Jarlennnn** [comment]
I'm seeing the same issue.
Version 4.2.0. 
AddBlazoredLocalStorage is found but AddBlazoredLocalStorageAsSingleton is not.
Tried cleaning, rebuilding, deleting Obj and Bin

**Comment by Jarlennnn** [comment]
> I'm seeing the same issue. Version 4.2.0. AddBlazoredLocalStorage is found but AddBlazoredLocalStorageAsSingleton is not. Tried cleaning, rebuilding, deleting Obj and Bin

I see not that is is not available in 4.2.0.. only in preview for 4.3.0..
Maybe it should not be on README until implemented...

cheers
