### ISSUE TITLE
[Feature Request] Change protection level of Blazored.LocalStorage.LocalStorageService from internal to public

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [Blazored/LocalStorage#196]
Hello, I want to create my own LocalStorageService based on current's Blazored LocalStorageService class:
```
public class MyLocalStorageService : Blazored.LocalStorage.LocalStorageService
{
}
```
I can't do this because the base class is marked as internal.

Is it a bad idea to change it from internal to public? It doesn't seem smart to reimplement the whole class.

In the end, I want to inject a service in my own `LocalStorageService` that puts a prefix in the keys.

**Comment by chrissainty** [comment]
The reason for this is so I can play around with how that class works without breaking others. If I make it public I might make a change that breaks something in a sub-class and I don't want that restriction. 

Based on what you want to do, it sounds like a better option would be to provide a configuration option to prefix key values with a custom string?

**Comment by FelipeCostaGualberto** [comment]
When you say "Configuration Option", you mean [options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0) or literally `appsettings.json`?
Anyway, I don't see how I would use them to prefix my keys without having access to the `Blazored.LocalStorage.LocalStorageService` class.

**Comment by chrissainty** [comment]
I was thinking the options pattern. You could define your prefix when registering the service then it would automatically prefix all keys with whatever you specify. You could just prefix the key before calling the method on the local storage service, you pass the key name in after all.

**Comment by FelipeCostaGualberto** [comment]
Hi, I don't know how to do that.
When I try to use the overload of the service when adding it:

`services.AddBlazoredLocalStorage(options => options...`

The only option I got is 
```
namespace Blazored.LocalStorage.StorageOptions
{
    public class LocalStorageOptions
    {
        public JsonSerializerOptions JsonSerializerOptions { get; } = new JsonSerializerOptions();

    }
}
```

How would I add a prefix?

**Comment by chrissainty** [comment]
That functionality doesn't exist yet. That was what I was suggesting would resolve your issue.

**Comment by chrissainty** [comment]
As there was no reply here I'm going to close this issue due to inactivity.
