### ISSUE TITLE
Can a Blazor Server Side controller save to local storage and a razor page get it

### ISSUE THREAD

**Issue by dgxhubbard** [Blazored/LocalStorage#203]
I have a Blazor Server Side app and it has a controller. In an action the controller saves to 
local storage:

LocaleStorage.SetItemAsync <MyData> ( "foo", myData );

Can a blazor component access this data:

MyData myData = null;
if ( await LocalStorage.ContainKeyAsync ( "foo" )  )
    myData = await LocalStorage.GetItemAsync <MyData> ( "foo" );

**Comment by chrissainty** [comment]
Yes. Local storage is a general storage feature of browsers.
