### ISSUE TITLE
how inject in Code behind in program.cs

### ISSUE THREAD

**Issue by rajeshsws** [Blazored/LocalStorage#215]
blazor.webassembly.js:1  System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ProXDashBoardPWA.masterclass.Gettoken() in D:\MAUI Projects\Latest Dashboard\ProXDashBoardPWA\ProXDashBoardPWA\masterclass.cs:line 22
   at Program.Main(String[] args) in D:\MAUI Projects\Latest Dashboard\ProXDashBoardPWA\ProXDashBoardPWA\Program.cs:line 36
   --- End of inner exception stack trace ---
     [Inject]  public static ILocalStorageService? localStorage { get; set; }
   builder.Services.AddScoped<masterclass>();
   masterclass masterclass = new masterclass(localStorage);
   string test = await masterclass.Gettoken();

  public class  masterclass: ComponentBase
    {
         
        ILocalStorageService _localStorageService;

        public masterclass(ILocalStorageService  localStorage)
        {
            _localStorageService = localStorage;

          
        }

      
        public async Task<string> Gettoken()
        {
            
            return await _localStorageService.GetItemAsync<string>("LocalAPI");
        }

    }

**Comment by chrissainty** [comment]
I'm sorry @rajeshsws but I can't see what the issue is from what you've provided. Can you provide a minimal repro of the issue.

**Comment by rajeshsws** [comment]
@chrissainty I found the solution my problem is solved. Thank you very much.

 [Inject]
    public static IJSRuntime JSRuntime { get; set; }
 private static async Task Main(string[] args)
    {
  var jsRuntime = builder.Services.BuildServiceProvider().GetRequiredService<IJSRuntime>();
 var localStorageValue = await jsRuntime.InvokeAsync<string>("localStorage.getItem", "LocalAPI");
}
Its solved my problem .
Thank you very much

**Comment by chrissainty** [comment]
Just to be clear. That's not using this library, you're just calling JS interop code directly.

**Comment by paulvanbladel** [comment]
Chris,
The problem the OP is facing is about correct usage of Dependency Injection (DI) in blazor.
The OP is trying to use constructor injection which is, as far as I know not supported in blazor. I might sound as if i knew this for years, but i just discovered it :)
When using the code behind approach, you must your property injection instead of constructor injection.

So, let's focus on the canonical counter example in each vanilla blazor app with following screen, split between markup and code behind:
counter.blazor:

```
@page "/counter"

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
```
The code behind file: counter.razor.cs:
```
using Blazored.LocalStorage;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

namespace TelerikBlazorAppWithLocalStorage.Client.Pages
{
    public partial class Counter
    {
        int currentCount = 0;

        [Inject]
        public ILocalStorageService LocalStorageService { get; set; }
        async void IncrementCount()
        {
            currentCount++;
            await LocalStorageService.SetItemAsync("count", currentCount);
        }
        protected override async Task OnInitializedAsync()
        {
            currentCount = await LocalStorageService.GetItemAsync<int>("count");
            await base.OnInitializedAsync();
        }
    }
}

```
The clue is to properly decorate the injected services with the Inject attribute.
HTH.
cheers
paul.

**Comment by chrissainty** [comment]
Thanks for spotting that, @paulvanbladel. I missed that when I first looked at the issue 🤦‍♂️. The irony is I've written a few in-depth articles about DI in Blazor and pointed out this very mistake 🤦‍♂️🤦‍♂️🤣 

Great explanation for others coming across this issue. 👍
