### ISSUE TITLE
AddBlazoredLocalStorage() add public setter for options.JsonSerializerOptions

### ISSUE THREAD

**Issue by rf-0** [Blazored/LocalStorage#216]
**Is your feature request related to a problem? Please describe.**
Currently we need to set each `JsonSerializerOptions` manually independently if we have a static method already defined.

**Describe the solution you'd like**
Allow for `options.JsonSerializerOptions` to be set so a static `JsonSerializerOptions` config can be reused instead of setting each property again.

`Blazored.LocalStorage.StorageOptions.LocalStorageOptions.JsonSerializerOptions`

` public JsonSerializerOptions JsonSerializerOptions { get; **set;** } = new JsonSerializerOptions();`

**Describe alternatives you've considered**
Currently mapping everything manually (converters etc)

**Additional context**
Cleaner centralized code.

**Comment by chrissainty** [comment]
Hi @rf-0, this makes a lot of sense. I'm not sure why I removed the setter now in all honesty. Thank you for also raising a PR for this.

**Comment by chrissainty** [comment]
I've merged your PR @rf-0 and just pushed a new release with the change. Thank you again for your help on this one.
