### ISSUE TITLE
[Bug] ASP.NET Core AggregateException on startup after injecting BlazorLocalStorage with dependency injection

### ISSUE THREAD

**Issue by albinalm** [Blazored/LocalStorage#222]
**Describe the bug**
When I am running builder.Services.AddBlazoredLocalStorage() the app throws AggregateException on startup. (See screenshot)

I've tried to just create a flat out empty project using the same SDK and .NET version with just BlazorLocalStorage and getting the same problem.

**To Reproduce**
1. Create a ASP.NET Core Web Application
2. Ensure you use SDK 7.0
3. Framework: net7.0

**Screenshots**
![image](https://github.com/Blazored/LocalStorage/assets/70197523/f9014444-dc8a-4ba7-949c-b0c63ec85f77)

**Hosting Model (is this issue happening with a certain hosting model?):**
- ASP.Net Core Web Application

**Comment by chrissainty** [comment]
Are you attempting to add Blazored Local Storage to a Blazor project or just an ASP.NET Core Web Application? If it's the later, the packages only work in Blazor projects.

**Comment by chrissainty** [comment]
I'm going to close this as there hasn't been any further communication.
