### ISSUE TITLE
.Net 8 RenderMode.InteractiveServer CustomAuthenticationStateProvider[Bug]

### ISSUE THREAD

**Issue by HuaFangYun** [Blazored/LocalStorage#232]
![image](https://github.com/Blazored/LocalStorage/assets/30250585/48d0b875-a699-4d97-bd7e-5d206f09a377)
![d5a9724ff5de236f4dd6689b6c6ca55](https://github.com/Blazored/LocalStorage/assets/30250585/81436baa-5c06-4528-88fe-974755e76499)
Please tell me how to solve this bug. Thank you.

**Comment by daohunliwei** [comment]
I have the same problem, but I haven't found a solution.
