### ISSUE TITLE
[Bug] Can't use local storage in a SSR

### ISSUE THREAD

**Issue by ankainn** [Blazored/LocalStorage#239]
**Describe the bug**
In my login page im using HTTPcontext to authenticate user and i can do that only on static render, but i cant store my data in local storage because of that.
InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

I'm using Blazor Web App NET8. 
Any ideas how can i solve my problem?

**Comment by chrissainty** [comment]
You'll need to change your approach. Just to be clear, this isn't an issue with the library but rather that you're trying to access local storage from the server. This isn't anything new in Blazor when using pre-rendering.

**Comment by mxmissile** [comment]
Does `SessionStorage` work with static SSR?
