### ISSUE TITLE
2.0.8 contains a tsconfig.json

### ISSUE THREAD

**Issue by Kim-SSi** [Blazored/LocalStorage#28]
The NuGet package contains a tsconfig.json that I believe is included by mistake.
The file as far as I can see doesn't do anything and the package does not reference TypeScript as a dependency.
This extra file breaks my projects.

**Comment by chrissainty** [comment]
Hi @Kim-SSi, if you update to the latest version this should now be resolved.

**Comment by Kim-SSi** [comment]
Brilliant. Thant fixed it. Thank you.
