### ISSUE TITLE
add Exist Method

### ISSUE THREAD

**Issue by julienGrd** [Blazored/LocalStorage#35]
Hi, and thanks for your work !
can you add an "exist" method on your library ?
it's normally not so difficult, something like that
````
public async Task<bool> Exist(string key)
        {
            if (string.IsNullOrEmpty(key))
                throw new ArgumentNullException(nameof(key));

            var serialisedData = await _jSRuntime.InvokeAsync<string>("localStorage.getItem", key);

            return serialisedData != null;
        }
````
thanks !

Julien

**Comment by chrissainty** [comment]
I'll look at getting this added @julienGrd. Also happy to take a PR if you fancy having a go at it?

**Comment by julienGrd** [comment]
Hi Chris, yeah I can commit this kind of stuff by myself without problem !
By the way, if there is some projects of the blazor community which need helps, i will be happy do help them, i work on blazor since february and I love it, I use a lot of works of the community so it's time to give back to the community (I work at full time so I would do what I can :-) )

**Comment by julienGrd** [comment]
OK the PR is make, say me if there is something with my code !

**Comment by julienGrd** [comment]
Solved by https://github.com/Blazored/LocalStorage/pull/37
