### ISSUE TITLE
Timespan serialization support

### ISSUE THREAD

**Issue by julienGrd** [Blazored/LocalStorage#38]
Hello Chris, I see there is an issue with timespan and the new JsonSerializer .NET (see https://github.com/dotnet/corefx/issues/38641)
Indeed, with the actual code, if I set a timespan item, it write this string representation hh:mm:ss
If i try to read this timespan with GetItem, i get an empty Timepsan wathever the value (without exception)

I have a PR ready for that wich add a JsonConverter dedicated to the timespan. It write the timespan at the standard string representation (d.hh:mm:ss:FFF) and read it with the same format.
It works well, but i have some interrogations on the behavior when the string is not in correct format (for example, a timespan store  with only hh:mm:ss, in cas the value was not written with this library). There is few solutions:
- I launch an exception like format Exception explaining the entry is not at a correct timespan format
- i hide the problem and return a zero timespan (not a fan about this one)
- i try different format (for example try to parse with standard format, if not works with the hh:mm:ss format, etc). At the end return exception or zero timespan if not works.

What do you think about that ?

thanks !

Julien

**Comment by chrissainty** [comment]
Hi Julien,

That would be great to take a PR for this issue. In regards to your solutions, I would suggest going with the first one. I think it's the clearest to the user and doesn't require any guesswork on our part. 

Cheers,
Chris
