### ISSUE TITLE
Question: Work with any C# WASM?

### ISSUE THREAD

**Issue by dgerding** [Blazored/LocalStorage#40]
Hi,
I'm thinking of trying out [Uno Platform](http://platform.uno) and wondered if anyone knew or had tried Blazored LocalStorage with a Uno.Platform project.  Going to go give it a shot but figured I'd ask. 
Thanks,
Dave G

**Comment by chrissainty** [comment]
Hi, I would doubt that it will work with Uno as it relies on Blazors way of doing JavaScript interop. But let me know how you get on.

**Comment by chrissainty** [comment]
I'm going to close this issue as there isn't really anything outstanding to do but feel free to comment about how you get on if you do try,
