### ISSUE TITLE
Feature Request: GetStorageUsed{Async}

### ISSUE THREAD

**Issue by Discovery-support** [Blazored/LocalStorage#44]
Is there anyway that I can determine **how much** LocalStorage has been used so far?  I have no idea how much data is being stored since it has been Json serialized and is not in its original format.

If this is not possible, then is it a case of catching an 'out-of-memory' exception if I should exceed the amount available? 

I would obviously much prefer a GetStorageUsed{Async} method.

Russ Sherlock

**Comment by chrissainty** [comment]
Hi Russ,

There is no built-in way to check the amount of local storage being used. I've done a bit of poking around and there are some methods to roughly calculate it. We'll look to get this added to the library.

**Comment by chrissainty** [comment]
I'm going to close this as after more investigation, calculating local storage limits is very error prone and often highly inaccurate.
