### ISSUE TITLE
Problems with LocalStoreage bigger than 30 KByte

### ISSUE THREAD

**Issue by baer999** [Blazored/LocalStorage#46]
[BlazorApp2.zip](https://github.com/Blazored/LocalStorage/files/3840909/BlazorApp2.zip)

Getting this Exception:

2019-11-11 13:10:06.6198 Error System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Blazored.LocalStorage.LocalStorageService.GetItemAsync[T](String key)
   at PegasusV6.Pages.Components.Basket.BasketComponent.OnAfterRenderAsync(Boolean firstRender) in C:\SOURCE\PegasusV6\PegasusV6\Pages\Components\Basket\BasketComponent.razor:line 88 

When try getting LocalStorage that is bigger than 30 KB and I don't have a clue whats the reason...

on LINE:
**var data = await LocalStorage.GetItemAsync<BasketState>("Basket");**

Is there a known limitation or can I get rid of it anyhow?

SOURCE in a razor file:

```   
protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        My.Log.Info($"BasketComponent.OnAfterRender({firstRender})");

        try
        {
            if (firstRender)
            {
                var data = await LocalStorage.GetItemAsync<BasketState>("Basket");

                // TODO: Fill with correct prices

                if (data != null)
                {
                    AppState.Basket = data;
                    StateHasChanged();
                }

                AppState.Basket.OnBasketChanged -= new Action (async () => await UpdateBasketAtLocalStorage());
                AppState.Basket.OnBasketChanged += new Action (async () => await UpdateBasketAtLocalStorage());
            }
        }
        catch (Exception ex)
        {
            My.Log.Error(ex);
        }
    }
```

**Comment by baer999** [comment]
you can see in attached project when going to COUNTER.razor and click a few times on Counter Button.

Then comes "Attempt to reconnect to server" and GetItemAsync is getting timeout...

How can I fix this?

**Comment by chrissainty** [comment]
Hi @baer999, yes the browser does have a limit on what it can hold but it's around 10mb if remember correctly. This is a bit of an odd one. I'll need to do some digging to try and work out where this issue lies.

**Comment by Tagwerk-Berlin** [comment]
I do have the same problem. I can save about 10 items of an array - that's it.

**Comment by Komawi** [comment]
I noticed outside your project that Chrome has an issue passing large data back to Blazor, regardless of your project. In Edge I did not have this issue.

I stumbled upon this issue while taking a picture with the webcam and trying to send it to my Blazor application. The base64 encoded string representation of the PNG image is too long for Chrome to process correctly. As I said, Edge can handle this data size.

**Comment by chrissainty** [comment]
@Komawi Thanks for letting me know.

@Tagwerk-Berlin @baer999 Are you using chrome? If so could you test it in Edge or Firefox and see if you still see the same behaviour?

**Comment by chrissainty** [comment]
Unfortunately, I've not been able to reproduce this behaviour and as I've not had any further information back I'm going to close this issue for now. If you can provide some extra information then please feel free to re-open.

**Comment by Tagwerk-Berlin** [comment]
Sorry for the delay - yes, it seems that chrome has this issue with large data. Thank you.

**Comment by EmilAlipiev** [comment]
This has nothing to do with Chrome or any other browser. But MS limitation with Signal R. I think that default limit is 32kb, thats why any bigger string or object greater than 32 bit will close the signal R connection. thats why browser keeps returning connecting again message. 
 here is the workaround. https://github.com/Blazored/SessionStorage/issues/51#issuecomment-939824923
