### ISSUE TITLE
Try Catch methods Like GetItemAsync

### ISSUE THREAD

**Issue by baer999** [Blazored/LocalStorage#50]
Otherwise you will get complete shutdown of the page if a JavaScript call fails.

You can see here a sample stack trace of my error:

Diese Ausnahme wurde ursprünglich bei dieser Aufrufliste ausgelöst:
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Threading.Tasks.ValueTask<TResult>.Result.get()
	Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation<T>(string, object[])
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	Blazored.LocalStorage.LocalStorageService.GetItemAsync<T>(string)
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    ...

**Comment by chrissainty** [comment]
What do you think should happen to the exception?

**Comment by MadTiger2409** [comment]
There is a LINQ to XML, LINQ to Excel and other, so maybe we can go with this direction (make it LINQ to LocalStorage) and then it will be clear when you gen exception and what to do with this.

**Comment by baer999** [comment]
Hello Michel,

 

sounds interesting, my problem is just the exception in that module and I don’t know how to handle it correct.

 

LINQ to LocalStorage sounds nice, but what would help there regarding Exception?

 

When thinking on LINQ I think of something like:

 

LocalStorage

.FirstOrDefault(x => x.Key == “Test”)

 

Or something like this.

 

Von: Michał B. <notifications@github.com> 
Gesendet: Sonntag, 29. Dezember 2019 09:51
An: Blazored/LocalStorage <LocalStorage@noreply.github.com>
Cc: baer999 <baer999@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Blazored/LocalStorage] Try Catch methods Like GetItemAsync (#50)

 

There is a LINQ to XML, LINQ to Excel and other, so maybe we can go with this direction (make it LINQ to LocalStorage) and then it will be clear when you gen exception and what to do with this.

**Comment by MadTiger2409** [comment]
@baer999 The way you handle exception depends on how your app should act. When I was testing Blazor with this library, I wrapped some methods that for example returns null when trying to get some data and exception occurred.

But you mentioned **LocalStorage.FirstOrDefault(x => x.Key == “Test”)**. As we know, FirstOrDefault() will get first element that matches the criterion or will return null. So this will be a very predictable behavior.

**Comment by chrissainty** [comment]
@baer999 Do you know why you're getting this exception?

**Comment by baer999** [comment]
Right now I don’t know why and how these Exceptions are occurring:

 



 

 

And without handling them on my side of application there is a crash of application workflow….

 

Are you experiencing anything comparable and how do you handle it?

 

Thx!

 

Von: Michał B. <notifications@github.com> 
Gesendet: Sonntag, 29. Dezember 2019 09:51
An: Blazored/LocalStorage <LocalStorage@noreply.github.com>
Cc: baer999 <baer999@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [Blazored/LocalStorage] Try Catch methods Like GetItemAsync (#50)

 

There is a LINQ to XML, LINQ to Excel and other, so maybe we can go with this direction (make it LINQ to LocalStorage) and then it will be clear when you gen exception and what to do with this.

**Comment by chrissainty** [comment]
I would hazard a guess that there is an issue with deserialization of whatever it is you're trying to read out of local storage.

Can you provide an example of what you're doing?

**Comment by chrissainty** [comment]
As I've not heard anything back for a while I'm going to close this issue. Please re-open if you're still having a problem.
