### ISSUE TITLE
Sync local storage with browser account

### ISSUE THREAD

**Issue by FrancoisDotNet** [Blazored/LocalStorage#51]
Hi,

With local storage, users (and developers) don't have to deal with login and password !

I am wondering if there is a manner to sync this local storage accross devices ?
I know that some browsers can sync history and other data.

The idea is to defer authentication and data managment to browsers since with Blazor WebAssembly, the browser is the OS.

**Comment by chrissainty** [comment]
Hi, I'm not sure I completely understand what you're suggesting, but to answer your question, I don't believe local storage can be synced across devices.

**Comment by FrancoisDotNet** [comment]
I understand that local storage is an HTML standard but there is no HTML standard to sync storage.

I think that Chrome has an API for this : [chrome.storage](https://developer.chrome.com/extensions/storage). But I don't tested it because I am not confortable with javascript.

**Comment by chrissainty** [comment]
I'm not sure, to be honest. I'm going to close this issue and this is more of a brainstorming exercise than an issue with this library.

Best of luck with your investigation.
