### ISSUE TITLE
Registering the Service in a Blazor Webassembly Project

### ISSUE THREAD

**Issue by aikidoshi** [Blazored/LocalStorage#54]
Hi there,

The docs show how to add the service to a typical server side project, but I haven't been able to work out how to setup the service in a Blazor client-side (WASM) Project.

Please advise.

Regards,
Steve Bond

**Comment by chrissainty** [comment]
Hi Steve,

I've just pushed an update for the package and I've updated the samples and the readme to reflect the changes in Blazor WebAssembly. Let me know if you have any further issues.

**Comment by aikidoshi** [comment]
Perfect, thanks!
