### ISSUE TITLE
Can't consume service in webassembly project after 3.2.0-preview3

### ISSUE THREAD

**Issue by julienGrd** [Blazored/LocalStorage#61]
Hi Chris, I met a problem after upgrading my project in 3.2.0-preview3 (https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/)

the error i have is
````
Unhandled exception rendering component: Cannot consume scoped service 'Blazored.LocalStorage.ILocalStorageService' from singleton 'MyService'.

````
and indeed, i inject your ILocalStorageService in some services inject as singleton.

My project is dual mode serverside/webassembly, and by convention/logic i inject most of my services as singleton in webassembly and scoped in server side.

When i check how you register your service in AddBlazoredLocalStorage, i see you inject it as scoped.

I try to put all my services as scoped in my assembly project (i really don't want to do that, its just for test) and anyway at the end im unable to resolve all the dependency because the ILogger is still a singleton and i don't have control on this.

Microsoft don't really communicate on this update for this preview, but it look like more than a bug resolution than a regression, because for me even with the previous version it was not suppose to work (consume a scoped service from a singleton).

so what do you think about that ?
 - a simple resolution will be add a parameter to AddBlazoredLocalStorage to inject services as singleton if asked. I don't know if it in the good practice.

If you wan't to reproduce :
- upgrade your webassembly project to the last version (follow this https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/ then this https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/)
- create a simple service where you inject ILocalStorageService
- add this service as a singleton in program.cs
- inject it on your index.razor page
- launch your poject, it will crash  with this error in the developer console

I wait for your feedback, if you are OK with the resolution i speak a can suggest a PR (upgrading the package + parameter in AddBlazoredLocalStorage to inject services as singleton)

thank you !

Julien

**Comment by chrissainty** [comment]
Hi @julienGrd, I'm really surprised you were ever able to run code where you were injecting scoped services into singletons. The compiler should always have thrown an error as that shouldn't be allowed to happen.

In terms of your app, why do you choose to use different scoped between Blazor Server and Blazor WebAssembly? There is no difference between scoped and singleton in Blazor WebAssmebly. Hence the guidance from Microsoft to use scoped services as they will act the same between both hosting models.

I really don't see a reason to change our approach on this. Our services being added to the DI container as scoped is the correct configuration. If you really want to run a non-standard configuration, then instead of using the provided `AddBlazoredLocalStorage` helper for adding services, you can just add them manually with the configuration you choose.

```csharp
    Services.AddSingleton<ILocalStorageService, LocalStorageService>()
    Services.AddSingleton<ISyncLocalStorageService, LocalStorageService>();
```

**Comment by julienGrd** [comment]
> Hi @julienGrd, I'm really surprised you were ever able to run code where you were injecting scoped services into singletons. The compiler should always have thrown an error as that shouldn't be allowed to happen.

Yes that's why i was surprise also ! but it works ! until the last preview, that's why i think they resolve a bug

> In terms of your app, why do you choose to use different scoped between Blazor Server and Blazor WebAssembly? There is no difference between scoped and singleton in Blazor WebAssmebly. Hence the guidance from Microsoft to use scoped services as they will act the same between both hosting models.

OK it make sense, no problem for me to put all my services in scoped. i double check and if i put all my services scoped it work in the both modes

> 
> I really don't see a reason to change our approach on this. Our services being added to the DI container as scoped is the correct configuration. If you really want to run a non-standard configuration, then instead of using the provided `AddBlazoredLocalStorage` helper for adding services, you can just add them manually with the configuration you choose.

With passing all my service scoped, i don't have any problems, i close this issue, thanks for your help !

**Comment by robertdunaway** [comment]
chrissainty   I'm having the same problem.  So I'm not sure what I should change to make this work properly.  You share some code above but you imply this code was for working around and doing some custom implementation.

Do do we inject local storage so we can use it anywhere in our application, correctly?

**Comment by chrissainty** [comment]
Hi @robertdunaway, what exactly is your issue?

**Comment by robertdunaway** [comment]
I think this might have done the trick for me.  I use the BlazoredLocalService as part of my AppStateServce.  I made the change below and my AppStateService class was able to continue receiving the injected local state class.

           // builder.Services.AddSingleton<AppStateService>();
            builder.Services.AddScoped<AppStateService>();

**Comment by chrissainty** [comment]
Yes, that's because we register our service as scoped. Scopes services can't be injected into singletons.

**Comment by nssidhu** [comment]
After upgrading to .net 6 preview i started getting compiler error.

```
builder.Services.AddSingleton<ILocalStorageService, LocalStorageService>();
builder.Services.AddSingleton<ISyncLocalStorageService, LocalStorageService>();
```

![image](https://user-images.githubusercontent.com/3267605/123173281-fd26ae00-d443-11eb-878b-453b5ab2ddac.png)

and if i use the following line i get runtime error

` builder.Services.AddBlazoredLocalStorage();`

```
blazor.webassembly.js:1 System.AggregateException: One or more errors occurred. (Cannot consume scoped service 'Blazored.LocalStorage.ILocalStorageService' from singleton 'BlazorBaseApp.Client.Services.CustomAuthenticationStateProvider'.)
 ---> System.InvalidOperationException: Cannot consume scoped service 'Blazored.LocalStorage.ILocalStorageService' from singleton 'BlazorBaseApp.Client.Services.CustomAuthenticationStateProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScopeCache(ServiceCallSite scopedCallSite, CallSiteValidatorState state) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000096+0x13
```
