### ISSUE TITLE
[Bug-Regression] problem with integer serialization

### ISSUE THREAD

**Issue by julienGrd** [Blazored/LocalStorage#63]
Hello Chris, since the last version it seem there is a bug on the integer serialisation.
When i try to retieve the value, i have this exception (at leats on server side project)
Unable to cast object of type 'System.String' to type 'System.Nullable`1[System.Int32]'.'

To reproduce this (on your sample project for example)
````
<div class="row">
    <div class="col-md-4">
         <button class="btn btn-primary" @onclick="SaveInteger">set 5 in local storage</button>
    </div>
    <div class="col-md-4">
        <button class="btn btn-primary" @onclick="LoadInteger">read 5 in local storage</button>
    </div>

    <div class="col-md-4">
        <h5>Value in local storage</h5>
        @IntegerValue
    </div>
</div>
````
````
int? IntegerValue;
    async Task SaveInteger()
    {
        await localStorage.SetItemAsync("integerValue", 5);
    }
    async Task LoadInteger()
    {
        IntegerValue = await localStorage.GetItemAsync<int?>("integerValue");
        this.StateHasChanged();
    }
````
- click on the button to save the value
- click on the button to load the value => you will have the error (put "detailedErrors": true in the appsettings to see them)

its the same thing if the integer is not nullable

thanks !

**Comment by chrissainty** [comment]
Thanks for reporting this @julienGrd, I've recreated it per your instructions.

I'll work on getting a fix out ASAP.

**Comment by chrissainty** [comment]
I've just pushed a new release which should fix this issue.
