### ISSUE TITLE
`SetItem` (async) doesn't appear to trigger `window.onstorage`

### ISSUE THREAD

**Issue by chucker** [Blazored/LocalStorage#7]
Given a component with this:

```csharp
    private bool DarkMode { get; set; }

    public async void ToggleDarkMode(UIChangeEventArgs e)
    {
        await _SetDarkMode(!DarkMode);
    }

    private async Task _SetDarkMode(bool darkMode)
    {
        DarkMode = darkMode;

        await localStorage.SetItem("DarkMode", DarkMode);

        StateHasChanged();

        Console.WriteLine($"DarkMode is now: {DarkMode}");
    }
```

And an `index.html` snippet like this:

```javascript
    <script type="text/javascript">
window.onstorage = function (ev) {
    console.log(ev.key);
};
    </script>
```

* Invoking `_SetDarkMode` does show up/toggle the value in Chrome's Application tab. However, the `onstorage` event never fires that way.
* OTOH, if I _manually_ toggle the value from Chrome, the event _does_ fire.

So I'm wondering if Chrome does something else to 'commit' the value (there doesn't appear to be a function like `refresh()` or `save()`), or if this is perhaps a side effect of the code running in an async or wasm context.

**Comment by chrissainty** [comment]
As per the [docs](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onstorage) the onstorage event only fires when storage is updated from another document. 

For example, open the app in two tabs in Chome and make a change to localstorage on tab 1, the event will fire in tab 2.

I'm going to go ahead and close this as there doesn't seem to be a problem with Blazored.LocalStorage.
