### ISSUE TITLE
Serialize class to local storage

### ISSUE THREAD

**Issue by intech-paul** [Blazored/LocalStorage#71]
I have a class I would like to store:

            public class MyData
            {
                public string name;
                public string address;
                public int age;

                public MyData()
                {
                    name = "name";
                    address = "address";
                    age = 50;
                }
            }

            MyData mydata = new MyData();

to store it, I need to serilaize to string:
await localStorage.SetItemAsync("mydata",JsonConvert.SerializeObject(mydata));
this is fine, it works ok.
but when I read it back as a string, I get an error

            try{ 
            string text = await localStorage.GetItemAsync<string>("mydata");
            }
        catch (Exception ex)
        {
            exstring = ex.Message;
           return;
        }

The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1. address name

Is their anyway I can read the item back as a string and deserialize myself ?

**Comment by chrissainty** [comment]
You don't need to serialise the object, this library does that for you. The reason you're seeing the error is because your object has been serialised twice but only deserialised once.

**Comment by intech-paul** [comment]
If I write the class directly, all it stores is {} for the item, and no exception is thrown.
await localStorage.SetItemAsync("mydatareal",mydata);

**Comment by chrissainty** [comment]
Yes. Does that answer your question?

**Comment by intech-paul** [comment]
So the SetItemAsync can't write a class ?

**Comment by chrissainty** [comment]
I'm sorry I'm not following you. `SetItemAsync` serialises your class and the `GetItemAsync` deserialises it. You don't need to do any serialisation yourself.

**Comment by intech-paul** [comment]
Here's a test:

        await localStorage.SetItemAsync("mydata_asclass",mydata);
        await localStorage.SetItemAsync("mydata_astext",JsonConvert.SerializeObject(mydata));

The result:

![image](https://user-images.githubusercontent.com/56703036/79514539-800ee480-809a-11ea-823a-d38dfe0eb1f7.png)

I know that I don't need to do this, but it proves that the class is intact
        await localStorage.SetItemAsync("mydata_astext",JsonConvert.SerializeObject(mydata));

**Comment by chrissainty** [comment]
Thanks for clarifying this issue. I've just run your code and replicated what you're seeing. If I change the fields in your class to properties, everything works as expected.

Are you using NewtonSoft.Json to do your manual serialisation?

**Comment by intech-paul** [comment]
Yes, I have it working now as well, also with a List<> of classes inside the class which is also what I am needing to use:

    public class InputValues
    {
        public int index { get; set; }
        public float fvalue{ get; set; }

        public InputValues()
        { }

        public InputValues(int index,float fvalue)
        {
            this.index = index;
            this.fvalue = fvalue;
        }
    }

    public class MyData
    {
        public string name { get; set; }
        public string address { get; set; }
        public int age { get; set; }
        public List<InputValues> inputValues { get; set; }

        public MyData()
        {
            name = "name";
            address = "address";
            age = 50;

            inputValues = new List<InputValues>();
        }
    }

![image](https://user-images.githubusercontent.com/56703036/79517218-a8e6a800-80a1-11ea-8dd4-6b5ec8283640.png)


My original test was using Newtonsoft.Json.

Thankyou for helping with this issue.

**Comment by chrissainty** [comment]
Glad we got it sorted 🙂

**Comment by robertdunaway** [comment]
I'm having the same problem.  I literally want the string back from local storage.  I'm not sure why it can't do that since what it stored was a string.

Thoughts?

string serialized_appState;
serialized_appState = await _localStorage.GetItemAsync<string>("appState") ?? "";

{"User":{"UserID":"9b02-431f-ac46-cf116fa90cf9","UserName":"","FullName":"Bob D","IsAuthenticated":true,"AuthenticatedDateTime":"2020-05-06T21:08:19.6653581+00:00","CompanyName":"Production","TenantName":"PROD","IsActive":true,"Initials":"BD","Phone":"","IsSystemAdmin":true,"IsSystemDeveloper":true,"IsTenantAdmin":true,"ConnectionString":"","Token":"7de34799-9b26-47bb-9353-185a7ffeda0c"},"PageLoadTime":"0.304"}

I'm not sure what about this value cannot be returned from localStorage as a string.  

Bob

**Comment by intech-paul** [comment]
From what I found the Set/Get operations find the "{" as part of the first character as an indicator that it is to be a json string so has to be deserilaized into json.
Also, your class has to be defined with all items {get; set}

You are best to try to read/write strings as a basic test.

NOTE:
there is a breaking change on VS Version 16.6.0 Preview 5.0 that stops the local storage working when you run the app from within the IDE, if you run the blazor app directly from a browser with https://localhost:44370/. I have notified MS of this by the report a problem.

**Comment by robertdunaway** [comment]
This is great information.

At one time this worked.  I'm not sure when it stopped working because the app still functions without it.  Or am I imagining that?

Did it work with { at one time?

**Comment by intech-paul** [comment]
I could not get it to work when the string had a { in it, but I am not sure if that was my class definition or not.
"MyTestString" is a great place to start, also you can have a look at the local storage in the chrome Test Info (CTRL+SHIFT+I) 
Application, Local storage to see if the data is there or not.

![image](https://user-images.githubusercontent.com/56703036/81240998-26785500-905d-11ea-9a09-f2d4836c5107.png)

**Comment by robertdunaway** [comment]
There has got to be a way to get a string value out of it even if it is a JSON string.

I'm trying a few things without luck.  I can't even believe it's an issue.  Seems like something that should just work.

**Comment by robertdunaway** [comment]
If I figure it out I'll post it here.

**Comment by robertdunaway** [comment]
This seems to work but other things are breaking.  I'll check that out.

Just wanted to share that using object seems to help.

                    object serialized_appState;
                    //serialized_appState = await _localStorage.GetItemAsync<string>("appState");
                    serialized_appState = await _localStorage.GetItemAsync<object>("appState");

**Comment by robertdunaway** [comment]
That did the trick.  I can get the JSON string as object and when I'm ready to use it I can deserialize it into the class I need.

The Blazored.LocalStorage  has been a great tool.  Thanks.
Bob

**Comment by chrissainty** [comment]
@robertdunaway Can you please open a separate issue for your problem.
