### ISSUE TITLE
[Bug] Missing Dependency on System.Text.Json

### ISSUE THREAD

**Issue by Siphonophora** [Blazored/LocalStorage#72]
**Describe the bug**
Either the docs or the nuget package, is missing a dependency on System.Text.Json. The app will crash if I don't add the nuget package manually. 

**To Reproduce**
1. Create new blazor server template. 
1. Follow steps on docs to get setup and set a value in local storage. _Btw, the docs still have the @function directive instead of @code_
1. You get an error as soon as the first call to local storage happens.

**Expected behavior**
Preferably, this package should pull in System.Text.Json automatically.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by chrissainty** [comment]
Hi @Siphonophora, thanks for spotting the issue in the readme, I've now updated it. 

In terms of the dependency issue, I can't replicate it. I've created a new Blazor Server app and copied the instructions exactly as they are written in the readme and everything worked as expected. I've double-checked this on another Windows machine and on my MacBook just to make sure it wasn't something odd happening across OSs.

Could you try again and if possible on a different machine to see if this is a local issue?

**Comment by Siphonophora** [comment]
@chrissainty I tried it on my home machine and didn't get the error so I guess it was local.

Thanks for all these libraries (particularly Modal). I have been using them on some projects recently and they are all working well.
