### ISSUE TITLE
[Question] Serve side : random behavior

### ISSUE THREAD

**Issue by vd3d** [Blazored/LocalStorage#73]
Hi,

I have a strange situation when the GetItemAsync works for 10% of the cases!

It is a server-side blazor and it is called in OnAfterRenderAsync. The browser freeze for some time and display this message "attempting to reconnect to the server", then I got an empty result!

Here is my code:

```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);
        try
        {
            /*if (firstRender)*/
                _imageData = await _localStorage.GetItemAsync<string>("editor.imageData");
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }
    }
```

Do you have any idea ? Its weird :-P

**Comment by chrissainty** [comment]
No idea, can you replicate this issue in a new project?

**Comment by vd3d** [comment]
Indeed,

Not easy... but, if I pass a small set of datas, no problem !

Here I try to pass a big image from one page to another, it is way mode data !
And in this case... I have a 'kind' of deadlock :-(
