### ISSUE TITLE
[Bug] Dependency About System.Text.Json

### ISSUE THREAD

**Issue by m1nicrusher** [Blazored/LocalStorage#74]
**Describe the bug**
If I create a brand new project and then install ```Blazored.LocalStorage``` and start to use it straight away, it will throw an exception about ```File not found: System.Text.Json```

**To Reproduce**
1. Create a new Blazor project
2. Install ```Blazored.LocalStorage```
3. Create a service to manage local storage
4. Configure the service in Startup.cs (```services.AddBlazoredLocalStorage();``` and ```services.AddScoped<YourService>();```)
5. Inject the service to a page
6. Run your application
7. Exception

**Expected behavior**
I think it should be compatible with the library within .Net Core or it should install the dependency automatically. (I'm not sure if ```System.Text.Json``` is preinstalled but I can ```using``` it. If I was wrong  feel free to tell me!)

**Screenshots**
If I do not install ```System.Text.Json``` here's what I get
![image](https://user-images.githubusercontent.com/19246983/81364889-12e6f000-912a-11ea-8b29-4e01a5d011fb.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
I only tried:
 - Blazor Server

**Additional context**
I'm using:
- Microsoft Visual Studio Community 2019 version 16.4.5
- .NET Core 3.1

**Comment by chrissainty** [comment]
@m1nicrusher - Please refer to issue #72. This seems to be a local issue on some peoples machines.
