### ISSUE TITLE
Blazor wasm local storage not working when started from VS IDE 16.6.0 Preview 5&6

### ISSUE THREAD

**Issue by intech-paul** [Blazored/LocalStorage#75]
Breaking change on 16.6.0 preview 5&6

When you start a blazor wasm app from the vs ide, it can't see any local storage values. It can save and then see its own storage values. Then if you close the app & start it again from the ide, the storage data is not there.

If the app is started directly from chrome using localhost address, the local storage works properly.

An issue has been created with the VS team:
https://github.com/dotnet/aspnetcore/issues/21642

**Comment by chrissainty** [comment]
Thanks for the heads up on this @intech-paul. It seems it’s more a potential bug with VS than us, is that correct?

**Comment by chrissainty** [comment]
As I've not heard back I'm going to close this issue as there doesn't appear to be anything for us to do.

**Comment by intech-paul** [comment]
This issue has been corrected in the latest update of Visual Studio:
Version 16.7.0 Preview 1.0
