### ISSUE TITLE
[Question] getting Error : Unable to resolve service for type 'Blazored.LocalStorage.LocalStorageService'

### ISSUE THREAD

**Issue by nssidhu** [Blazored/LocalStorage#76]
**Please be sure to check the readme file before raising an issue.**
I am trying to use Blazor storage library in Blazor Hosted WebAssembly.

 ```
public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");

            builder.Services.AddAuthorizationCore();
            
            builder.Services.AddTransient(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

           
            builder.Services.AddBlazoredLocalStorage();

            builder.Services.AddBlazoredSessionStorage();

            builder.Services.AddScoped<AppStateInfo,AppStateInfo>();
            builder.Services.AddScoped<CustomAuthenticationStateProvider>();
            builder.Services.AddScoped<AuthenticationStateProvider>(provider =>
                  provider.GetRequiredService<CustomAuthenticationStateProvider>());
                      
            builder.Services.AddOptions();
            var host = builder.Build();
       
            await host.RunAsync();
        }
    }
```

Error i get is as follow
 Unhandled exception rendering component: Unable to resolve service for type 'Blazored.LocalStorage.LocalStorageService' while attempting to activate 'myCustomApp.Services.CustomAuthenticationStateProvider'.
System.InvalidOperationException: Unable to resolve service for type 'Blazored.LocalStorage.LocalStorageService' while attempting to activate 'myCustomApp.CustomAuthenticationStateProvider'.

My Constructor looks like this and class is in the Blazor Client Project
  ```
public CustomAuthenticationStateProvider(Blazored.LocalStorage.LocalStorageService LocalStorage,
            Blazored.SessionStorage.SessionStorageService SessionStorage, AppStateInfo AppStateInfo, HttpClient Http)
        {
            _localStorage = LocalStorage;
            _SessionStorage = SessionStorage;
            _appStateInfo = AppStateInfo;
            _Http = Http;

        }
```

**Comment by chrissainty** [comment]
As per the readme, you need to inject `ILocalStorageService` not `LocalStorageService`

**Comment by aristocharisma** [comment]
Hi Chrissainty i followed a Blazor train video tutorial to add Authentication to my WebAssembly with adminlte App now i am asl getting this error Unable to resolve service for type 'Blazored.LocalStorage.LocalStorageService and the issue of the I i dont have that fault
