### ISSUE TITLE
[Bug] Changed event doesn't fire across tabs

### ISSUE THREAD

**Issue by Eonasdan** [Blazored/LocalStorage#83]
**Describe the bug**
The change event doesn't seem to fire across tabs as described. Even the sample client app doesn't work for me in both Chrome and Edge (chromium).

**To Reproduce**
1. Load the sample client app and run
1. Duplicate or open a new tab
1. In tab 1 set a value
1. Observe no changes in tab 2.

**Expected behavior**
I was hoping the event would fire and update each tab.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by chrissainty** [comment]
Hi @Eonasdan, this isn’t a bug the event isn’t designed to fire across tabs. The Changing event is a C# event, when you open a different tab you’re running another instance of the app. There is no way for it to know about an event in the other instance.

**Comment by Eonasdan** [comment]
hmm I thought it was supposed to be something like `window.addEventListener('storage', () => {` ?

**Comment by chrissainty** [comment]
There is a JavaScript event, I assume you’re thinking of [this one](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event). This is fired automatically by the browser but we don’t hook into it in any way. As I said, all our events are in C#. 

If this is what you’re trying to hook onto then you would need to do this via JavaScript interop.

**Comment by pekspro** [comment]
Here is an example how to set this up. Note that the event will be triggered in **other** tabs, not the tab were the storage has been changed.

In JavaScript:

```JS
window.addEventListener('storage', function (e) {
    if (e.storageArea === localStorage) {
        if (e.key !== 'i18next.translate.boo') {
            DotNet.invokeMethodAsync('MyAssembly', 'LocalStorageChanged', e.key);
        }
    }
});
```

`i18next.translate.boo` has something to do with translations and is used by Blazor. `MyAssembly` should be the name of the assembly.

In C#:

```CS
using Microsoft.JSInterop;

public static class JavaScriptCallbacks
{
    [JSInvokable]
    public static Task LocalStorageChanged(string? key)
    {
        Console.WriteLine($"Method MyMethod has been invoked with key: {key}");
        return Task.CompletedTask;
    }
}
```
