### ISSUE TITLE
syntax for a "using" in a c# class

### ISSUE THREAD

**Issue by sonofdust1215** [Blazored/LocalStorage#86]
Love the LocalStorage, thank you so much.   I would like to use it in a data service class instead of just razor pages.  What would be the syntax for putting it in a using?

**Comment by chrissainty** [comment]
You can inject the ILocalStorageService into a class and use it the same way you would in a component. Just be careful about when the class is used as if it’s called during prerendering, for example, you’ll end up with an exception.
