### ISSUE TITLE
Why local storage is empty after refresh the page

### ISSUE THREAD

**Issue by arunc700** [Blazored/LocalStorage#87]
Hi Team , I am trying to use local storage in my demo application and successfully implemented as you suggested but when i refresh the page local storage is getting empty.
Could you please suggest?

**Comment by chrissainty** [comment]
Hey @arunc700, could you please provide some code showing what you’re doing.

**Comment by arunc700** [comment]
Below the code is using when user is getting logged in. 

        public async Task MarkUserAsValidated(UserModel user)
        {
            await localStorageService.SetItemAsync("AccessToken", user.AccessToken);
            await localStorageService.SetItemAsync("RefreshToken", user.RefreshToken);

            var identity = GetClaimsIdentity(user);

            var claimsPrincipal = new ClaimsPrincipal(identity);

            NotifyAuthenticationStateChanged(Task.FromResult(new AuthenticationState(claimsPrincipal)));

        }


This code is working as expected but somewhere when i refresh the page and try to refresh the page so GetAuthenticationStateAsync() get executed in CustomAuthenticationStateProvider.cs and localStorageService.GetItemAsync is returning null.

     public async override Task<AuthenticationState> GetAuthenticationStateAsync()
        {           
            var accessToken = await localStorageService.GetItemAsync<string>("accessToken");
            ClaimsIdentity identity =new ClaimsIdentity();
            if (accessToken != null && accessToken != string.Empty)
            {
                var response = await accountService.GetUserByAccessTokenAsync(accessToken);
                if (response.Result != null)
                {
                    var user = response.Result.Result;                    
                    identity = GetClaimsIdentity(user);
                } 
            }   
            var claimsPrincipal = new ClaimsPrincipal(identity);
            return await Task.FromResult(new AuthenticationState(claimsPrincipal));
        }

**Comment by chrissainty** [comment]
Looking at your code you have different casing on your key. When saving its “Access Token”, when retrieving its “accessToken”. Could be the issue.

**Comment by arunc700** [comment]
Thanks for you answer. Yes you correct. i was putting wrong key.
