### ISSUE TITLE
 Does not work width 'Console.WriteLine'

### ISSUE THREAD

**Issue by qcjxberin** [Blazored/LocalStorage#9]
`
Console.WriteLine($"Value for key {e.Key} changed from {e.OldValue} to {e.NewValue}");
`
The above code output statement does not seem to work, and does not output data in the console.

**Comment by chrissainty** [comment]
Hi @qcjxberin, it's definitely working, have you run the sample project in the repo?

**Comment by chrissainty** [comment]
I'm guessing as there is no reply that you got things working so I'm going to go ahead and close this.
