### ISSUE TITLE
[Question] Can't get variable

### ISSUE THREAD

**Issue by AsinPetrov** [Blazored/LocalStorage#90]
Hello! I created a new Blazor Server project, I set up the project as it should, but my variable is empty.
Here is my code part in razor file. And next photo is a part of Startup.cs file
<img width="313" alt="code" src="https://user-images.githubusercontent.com/49500051/85235008-4b146a80-b41a-11ea-893f-8b1cbf6adcb2.png">
<img width="377" alt="services" src="https://user-images.githubusercontent.com/49500051/85235025-6f704700-b41a-11ea-9217-5dfe404df7d4.png">

**Comment by chrissainty** [comment]
Hey @AsinPetrov, did you inject the LocalStorage service into your component?

**Comment by AsinPetrov** [comment]
> Hey @AsinPetrov, did you inject the LocalStorage service into your component?

Yes, I injected it.

**Comment by chrissainty** [comment]
Are you seeing any errors in the console?

**Comment by AsinPetrov** [comment]
> Are you seeing any errors in the console?

No, I application is working, but after a few saves my save item is equal to null.

**Comment by chrissainty** [comment]
After a few saves? So it does work initially, at least for a while? Then it breaks?

**Comment by AsinPetrov** [comment]
> After a few saves? So it does work initially, at least for a while? Then it breaks?

Yes, the first time it saves value correctly, after that it saves only null. Could this be due to the fact that I'm using a Blazor Server-Side?

**Comment by AsinPetrov** [comment]
> After a few saves? So it does work initially, at least for a while? Then it breaks?

Also it can work fine after a null variable, but after next save it breaks again.

**Comment by AsinPetrov** [comment]
> After a few saves? So it does work initially, at least for a while? Then it breaks?

I just made a new Blazor WebAssembly project and it worked for me. I also made a new Blazor Server project, but it didn’t work.

**Comment by chrissainty** [comment]
That's really odd. I'll have to investigate this and try and reproduce the error. I assume you didn't add anything special to these new projects? They were essentially blank with minimal code to reproduce the error?

**Comment by AsinPetrov** [comment]
> That's really odd. I'll have to investigate this and try and reproduce the error. I assume you didn't add anything special to these new projects? They were essentially blank with minimal code to reproduce the error?

Yeah, it's a new Blazor Server project with this code:
<img width="310" alt="code" src="https://user-images.githubusercontent.com/49500051/85924218-6f000200-b899-11ea-830d-b0cbaa950a9e.png">

**Comment by chrissainty** [comment]
How are you saving? Of are you just refreshing the browser over and over again?

**Comment by AsinPetrov** [comment]
> How are you saving? Or are you just refreshing the browser over and over again?

I just open this page and the name variable is always empty.

**Comment by AsinPetrov** [comment]
That was my mistake, I had to add `StateHasChanged();`. Thanks for the library and for the help!
