### ISSUE TITLE
ISyncLocalStorageService 

### ISSUE THREAD

**Issue by PhilPJL** [Blazored/LocalStorage#93]
Just wondering why this is only available for Web Assembly?

I was using ILocalStorageService but this showed up a bug in SyncFusion controls.  Switching to the synchronous version has worked around the issue (hopefully they will fix this issue), but the issue occurs on Wasm and Server.  Having ISyncLocalStorageService available for Server could be useful.

**Comment by chrissainty** [comment]
Hi @PhilPJL, `ISyncLocalStorageService` doesn't work on Blazor Server as all calls have to go over the network and must be awaited. This isn't something we could, or probably would want, to get around.
