### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by drma-dev** [Blazored/LocalStorage#94]
* be able to save to session storage, instead of local storage - you may need to change the component name. :)

* have the possibility to encrypt the content before saving, to prevent the user from changing

* have some mechanism for placing an expiration time limit. for example: when calling the 'GetItemAsync' or 'ContainKeyAsync' methods, it would automatically remove the content

**Comment by chrissainty** [comment]
Hi @drma-dev thanks for your suggestions/questions, let me respond. 

- We have a separate package for session storage, Blazored SessionStorage. 
- Microsoft has an experimental package which encrypts values into local storage. I don’t think it is something we would add here as we’d just be reinventing the wheel. 
- Expiration time can be implemented by an individual developer right now by including that information in the object being added to local storage.

Hope that all makes sense. Happy to discuss anything further if it doesn’t 🙂.

**Comment by chrissainty** [comment]
Closing as there looks like there is nothing more to be done.
