### ISSUE TITLE
Conflict with System.text.json

### ISSUE THREAD

**Issue by bstorage** [Blazored/LocalStorage#95]
Not an issue with the SessionStorage code, but prevents its use in Blazor server apps.

Affects SessionStorage and LocalStorage.
I get the same log info from msbuild as reported here:
https://github.com/dotnet/aspnetcore/issues/23126

App runs as expected despite warning locally but crashes in hosted setting yielding:

An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Json, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Text.Json, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' 
at Blazored.SessionStorage.SessionStorageService..ctor(IJSRuntime jSRuntime, IOptions`1 options)

**To Reproduce**
Include library in trivial blazor server app. Compile.

Warning	MSB3277	Found conflicts between different versions of "System.Text.Json" that could not be resolved.  

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by larsk2009** [comment]
I am having the same issue on one of my sites. Only difference is, the issue only presents itself on the 'production' server and not on the local machine. Furthermore, I do not get any compile-time warnings. I also thought that it used to work, and cannot figure out what changed that caused it to break. I will do some further investigation myself, so nothing really helpfull from me at this point. Just wanted to know I am also having this issue.

**Comment by larsk2009** [comment]
I have figured out a solution which works for me, though I don't know what kind of implications it would have for the project: switching the library from .net standard to .net core. Inspiration for this came from [here](https://stackoverflow.com/a/61621923).

@bstorage you could make a nuget package from [this commit I made](https://github.com/larsk2009/LocalStorage/commit/162ebbb694a52e8a5c0ef7480019d636c9610418) and see if that fixes anything. 

@chrissainty is there any chance you will make this change? I don't know if this would break anything now or in the future?

**Comment by bstorage** [comment]
@larsk2009 Yes, that seems to work, thanks,.   larsk2009@162ebbb

**Comment by larsk2009** [comment]
@chrissainty Have you had a change to look at this? I know you are very busy so no worries if you haven't!

**Comment by chrissainty** [comment]
I think the best thing to do here is to add System.Text.Json as a direct dependency, this should resolve any issues I believe.

**Comment by chrissainty** [comment]
Sorry, it's taken a while to look at this. I've added a comment to the issue @bstorage linked in the opening comment, suggesting your fix @larsk2009. I'll wait to hear back from that before doing anything as I'm not sure what the impact of changing the target framework would be.

**Comment by AdamJonsson** [comment]
I myself fixed it by installing the [System.Text.Json from NuGet](https://www.nuget.org/packages/System.Text.Json/). I am really new to the whole .NET environment, so take this solution with some kilograms of salt 😅

**Comment by SQL-MisterMagoo** [comment]
@AdamJonsson has the best solution I think.

The conflict comes from Microsoft.NETCore.App which uses an older STJ library.
Overriding that in the project file to use the 4.7.2 version from nuget will resolve the conflict.

**Comment by hanskcr** [comment]
@AdamJonsson's solution worked for me too.
